function aa(e){var g=0;return function(){return g<e.length?{done:!1,value:e[g++]}:{done:!0}}}function ba(e){var g="undefined"!=typeof Symbol&&Symbol.iterator&&e[Symbol.iterator];return g?g.call(e):{next:aa(e)}}function w(e){if(!(e instanceof Array)){e=ba(e);for(var g,k=[];!(g=e.next()).done;)k.push(g.value);e=k}return e}var ca="function"==typeof Object.defineProperties?Object.defineProperty:function(e,g,k){if(e==Array.prototype||e==Object.prototype)return e;e[g]=k.value;return e};
function da(e){e=["object"==typeof globalThis&&globalThis,e,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var g=0;g<e.length;++g){var k=e[g];if(k&&k.Math==Math)return k}throw Error("Cannot find global object");}var y=da(this);function z(e,g){if(g)a:{var k=y;e=e.split(".");for(var a=0;a<e.length-1;a++){var c=e[a];if(!(c in k))break a;k=k[c]}e=e[e.length-1];a=k[e];g=g(a);g!=a&&null!=g&&ca(k,e,{configurable:!0,writable:!0,value:g})}}
function ea(){this.m=!1;this.h=null;this.i=void 0;this.g=1;this.v=0;this.l=null}function fa(e){if(e.m)throw new TypeError("Generator is already running");e.m=!0}ea.prototype.u=function(e){this.i=e};function ha(e,g){e.l={L:g,M:!0};e.g=e.v}ea.prototype.return=function(e){this.l={return:e};this.g=this.v};function A(e,g,k){e.g=k;return{value:g}}function ia(e){this.g=new ea;this.h=e}
function ja(e,g){fa(e.g);var k=e.g.h;if(k)return ka(e,"return"in k?k["return"]:function(a){return{value:a,done:!0}},g,e.g.return);e.g.return(g);return B(e)}function ka(e,g,k,a){try{var c=g.call(e.g.h,k);if(!(c instanceof Object))throw new TypeError("Iterator result "+c+" is not an object");if(!c.done)return e.g.m=!1,c;var b=c.value}catch(d){return e.g.h=null,ha(e.g,d),B(e)}e.g.h=null;a.call(e.g,b);return B(e)}
function B(e){for(;e.g.g;)try{var g=e.h(e.g);if(g)return e.g.m=!1,{value:g.value,done:!1}}catch(k){e.g.i=void 0,ha(e.g,k)}e.g.m=!1;if(e.g.l){g=e.g.l;e.g.l=null;if(g.M)throw g.L;return{value:g.return,done:!0}}return{value:void 0,done:!0}}
function la(e){this.next=function(g){fa(e.g);e.g.h?g=ka(e,e.g.h.next,g,e.g.u):(e.g.u(g),g=B(e));return g};this.throw=function(g){fa(e.g);e.g.h?g=ka(e,e.g.h["throw"],g,e.g.u):(ha(e.g,g),g=B(e));return g};this.return=function(g){return ja(e,g)};this[Symbol.iterator]=function(){return this}}function ma(e){function g(a){return e.next(a)}function k(a){return e.throw(a)}return new Promise(function(a,c){function b(d){d.done?a(d.value):Promise.resolve(d.value).then(g,k).then(b,c)}b(e.next())})}
function na(e){return ma(new la(new ia(e)))}z("Symbol",function(e){function g(b){if(this instanceof g)throw new TypeError("Symbol is not a constructor");return new k(a+(b||"")+"_"+c++,b)}function k(b,d){this.g=b;ca(this,"description",{configurable:!0,writable:!0,value:d})}if(e)return e;k.prototype.toString=function(){return this.g};var a="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",c=0;return g});
z("Symbol.iterator",function(e){if(e)return e;e=Symbol("Symbol.iterator");for(var g="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),k=0;k<g.length;k++){var a=y[g[k]];"function"===typeof a&&"function"!=typeof a.prototype[e]&&ca(a.prototype,e,{configurable:!0,writable:!0,value:function(){return oa(aa(this))}})}return e});function oa(e){e={next:e};e[Symbol.iterator]=function(){return this};return e}
z("Promise",function(e){function g(d){this.h=0;this.i=void 0;this.g=[];this.v=!1;var f=this.l();try{d(f.resolve,f.reject)}catch(h){f.reject(h)}}function k(){this.g=null}function a(d){return d instanceof g?d:new g(function(f){f(d)})}if(e)return e;k.prototype.h=function(d){if(null==this.g){this.g=[];var f=this;this.i(function(){f.m()})}this.g.push(d)};var c=y.setTimeout;k.prototype.i=function(d){c(d,0)};k.prototype.m=function(){for(;this.g&&this.g.length;){var d=this.g;this.g=[];for(var f=0;f<d.length;++f){var h=
d[f];d[f]=null;try{h()}catch(m){this.l(m)}}}this.g=null};k.prototype.l=function(d){this.i(function(){throw d;})};g.prototype.l=function(){function d(m){return function(n){h||(h=!0,m.call(f,n))}}var f=this,h=!1;return{resolve:d(this.H),reject:d(this.m)}};g.prototype.H=function(d){if(d===this)this.m(new TypeError("A Promise cannot resolve to itself"));else if(d instanceof g)this.J(d);else{a:switch(typeof d){case "object":var f=null!=d;break a;case "function":f=!0;break a;default:f=!1}f?this.G(d):this.u(d)}};
g.prototype.G=function(d){var f=void 0;try{f=d.then}catch(h){this.m(h);return}"function"==typeof f?this.K(f,d):this.u(d)};g.prototype.m=function(d){this.F(2,d)};g.prototype.u=function(d){this.F(1,d)};g.prototype.F=function(d,f){if(0!=this.h)throw Error("Cannot settle("+d+", "+f+"): Promise already settled in state"+this.h);this.h=d;this.i=f;2===this.h&&this.I();this.N()};g.prototype.I=function(){var d=this;c(function(){if(d.O()){var f=y.console;"undefined"!==typeof f&&f.error(d.i)}},1)};g.prototype.O=
function(){if(this.v)return!1;var d=y.CustomEvent,f=y.Event,h=y.dispatchEvent;if("undefined"===typeof h)return!0;"function"===typeof d?d=new d("unhandledrejection",{cancelable:!0}):"function"===typeof f?d=new f("unhandledrejection",{cancelable:!0}):(d=y.document.createEvent("CustomEvent"),d.initCustomEvent("unhandledrejection",!1,!0,d));d.promise=this;d.reason=this.i;return h(d)};g.prototype.N=function(){if(null!=this.g){for(var d=0;d<this.g.length;++d)b.h(this.g[d]);this.g=null}};var b=new k;g.prototype.J=
function(d){var f=this.l();d.A(f.resolve,f.reject)};g.prototype.K=function(d,f){var h=this.l();try{d.call(f,h.resolve,h.reject)}catch(m){h.reject(m)}};g.prototype.then=function(d,f){function h(r,t){return"function"==typeof r?function(D){try{m(r(D))}catch(l){n(l)}}:t}var m,n,v=new g(function(r,t){m=r;n=t});this.A(h(d,m),h(f,n));return v};g.prototype.catch=function(d){return this.then(void 0,d)};g.prototype.A=function(d,f){function h(){switch(m.h){case 1:d(m.i);break;case 2:f(m.i);break;default:throw Error("Unexpected state: "+
m.h);}}var m=this;null==this.g?b.h(h):this.g.push(h);this.v=!0};g.resolve=a;g.reject=function(d){return new g(function(f,h){h(d)})};g.race=function(d){return new g(function(f,h){for(var m=ba(d),n=m.next();!n.done;n=m.next())a(n.value).A(f,h)})};g.all=function(d){var f=ba(d),h=f.next();return h.done?a([]):new g(function(m,n){function v(D){return function(l){r[D]=l;t--;0==t&&m(r)}}var r=[],t=0;do r.push(void 0),t++,a(h.value).A(v(r.length-1),n),h=f.next();while(!h.done)})};return g});
z("Math.clz32",function(e){return e?e:function(g){g=Number(g)>>>0;if(0===g)return 32;var k=0;0===(g&4294901760)&&(g<<=16,k+=16);0===(g&4278190080)&&(g<<=8,k+=8);0===(g&4026531840)&&(g<<=4,k+=4);0===(g&3221225472)&&(g<<=2,k+=2);0===(g&2147483648)&&k++;return k}});z("Array.prototype.findIndex",function(e){return e?e:function(g,k){a:{var a=this;a instanceof String&&(a=String(a));for(var c=a.length,b=0;b<c;b++)if(g.call(k,a[b],b,a)){g=b;break a}g=-1}return g}});
function pa(e){function g(c,b,d,f){a.contextArray[c].bufferData(b,a.getArrayView(d),f)}var k=arguments;null==e.env.memory&&alert("You need to set memory in your importObject");null==e.WebGL&&(e.WebGL={});var a=e.WebGL;e.env.abort=function(c){for(var b=[],d=0;d<arguments.length;++d)b[d]=arguments[d];console.log("abort");console.log(a.getString(b[0]))};a.WEBGL_READY=!1;a.memory=e.env.memory;a.contextArray=[];a.textureArray=[];a.imageArray=[];a.programArray=[];a.shaderArray=[];a.bufferArray=[];a.frameBufferArray=
[];a.renderBufferArray=[];a.uniformLocationArray=[];a.vaoArray=[];a.SIZE_OFFSET=-4;a.ID_OFFSET=-8;a.CHUNKSIZE=1024;a.STRING_ID=1;a.RTTI_BASE=0;a.VAL_ALIGN_OFFSET=6;e.ARRAYBUFFERVIEW_DATASTART_OFFSET=4;e.ARRAY_LENGTH_OFFSET=12;a.NONE=0;a.ARRAYBUFFERVIEW=1;a.ARRAY=2;a.STATICARRAY=4;a.SET=8;a.MAP=16;a.ACYCLIC=32;a.VALUE_ALIGN_0=64;a.VALUE_ALIGN_1=128;a.VALUE_ALIGN_2=256;a.VALUE_ALIGN_3=512;a.VALUE_ALIGN_4=1024;a.VALUE_SIGNED=2048;a.VALUE_FLOAT=4096;a.VALUE_NULLABLE=8192;a.VALUE_MANAGED=16384;a.KEY_ALIGN_0=
32768;a.KEY_ALIGN_1=65536;a.KEY_ALIGN_2=131072;a.KEY_ALIGN_3=262144;a.KEY_ALIGN_4=524288;a.KEY_SIGNED=1048576;a.KEY_FLOAT=2097152;a.KEY_NULLABLE=4194304;a.KEY_MANAGED=8388608;a.createImage=function(c){console.log("createImage("+c+")");var b=new Image;b.ready=!1;b.onload=function(){b.ready=!0};b.src=a.getString(c);console.log("image.src="+b.src);c=a.imageArray.length;a.imageArray.push(b);return c};a.logi32=function(c){console.log("logi32="+c)};a.logf32=function(c){console.log("logf32="+c)};a.imageReady=
function(c){return a.imageArray.length<=c?!1:a.imageArray[c].ready};a.getView=function(c,b,d){var f=a.memory.buffer;if(d)switch(c){case 2:return new Float32Array(f);case 3:return new Float64Array(f)}else switch(c){case 0:return new (b?Int8Array:Uint8Array)(f);case 1:return new (b?Int16Array:Uint16Array)(f);case 2:return new (b?Int32Array:Uint32Array)(f);case 3:return new (b?BigInt64Array:BigUint64Array)(f)}throw Error("unsupported align: "+c);};a.getArrayInfo=function(c){var b=a.getInfo(c);if(!(b&
(a.ARRAYBUFFERVIEW|a.ARRAY|a.STATICARRAY)))throw Error("not an array: "+c+", flags="+b);return b};a.getValueAlign=function(c){return 31-Math.clz32(c>>>a.VAL_ALIGN_OFFSET&31)};a.getArrayView=function(c){var b=new Uint32Array(a.memory.buffer),d=b[c+a.ID_OFFSET>>>2];if(d>=b[a.RTTI_BASE>>>2])throw Error("invalid id: "+d);var f=b[(a.RTTI_BASE+4>>>2)+2*d];if(!(f&(a.ARRAYBUFFERVIEW|a.ARRAY|a.STATICARRAY)))throw Error("not an array: "+d+", flags="+f);d=31-Math.clz32(f>>>a.VAL_ALIGN_OFFSET&31);var h=f&a.STATICARRAY?
c:b[c+a.ARRAYBUFFERVIEW_DATASTART_OFFSET>>>2];c=f&a.ARRAY?b[c+a.ARRAY_LENGTH_OFFSET>>>2]:b[h+a.SIZE_OFFSET>>>2]>>>d;return a.getView(d,f&a.VAL_SIGNED,f&a.VAL_FLOAT).subarray(h>>>=d,h+c)};a.getString=function(c){var b=a.memory.buffer,d=new Uint32Array(b),f=c/4-2,h=d[f];if(1!==h)throw Error("not a string index="+c+" id="+h);d=d[f+1];return(new TextDecoder("utf-16")).decode(b.slice(c,c+d))};a.createContextFromCanvas=function(c,b){c=document.getElementById(a.getString(c)).getContext(a.getString(b),{alpha:!1});
b=a.contextArray.findIndex(function(d){return null==d});-1==b?(b=a.contextArray.length,a.contextArray.push(c)):a.contextArray[b]=c;return b};a.getSupportedExtensions=function(){alert("getSupportedExtensions is not currently supported")};a.getExtension=function(c,b){a.contextArray[c].getExtension(a.getString(b))};a.activeTexture=function(c,b){a.contextArray[c].activeTexture(b)};a.attachShader=function(c,b,d){a.contextArray[c].attachShader(a.programArray[b],a.shaderArray[d])};a.bindAttribLocation=function(c,
b,d,f){a.contextArray[c].bindAttribLocation(a.programArray[b],d,a.getString(f))};a.bindBuffer=function(c,b,d){a.contextArray[c].bindBuffer(b,a.bufferArray[d])};a.bindFramebuffer=function(c,b,d){a.contextArray[c].bindFramebuffer(b,a.framebufferArray[d])};a.bindRenderbuffer=function(c,b,d){a.contextArray[c].bindRenderbuffer(b,a.renderbufferArray[d])};a.bindTexture=function(c,b,d){a.contextArray[c].bindTexture(b,a.textureArray[d])};a.blendColor=function(c,b,d,f,h){a.contextArray[c].blendColor(b,d,f,
h)};a.blendEquation=function(c,b){a.contextArray[c].blendEquation(b)};a.blendEquationSeparate=function(c,b,d){a.contextArray[c].blendEquationSeparate(b,d)};a.blendFunc=function(c,b,d){a.contextArray[c].blendFunc(b,d)};a.blendFuncSeparate=function(c,b,d,f,h){a.contextArray[c].blendFuncSeparate(b,d,f,h)};a["bufferData<f32>"]=g;a["bufferData<f64>"]=g;a["bufferData<i32>"]=g;a["bufferData<u16>"]=g;a["bufferData<u8>"]=g;a.bufferSubData=function(c,b,d,f,h,m){a.contextArray[c].bufferSubData(b,d,a.getArrayView(f),
h,m)};a.checkFramebufferStatus=function(c,b){return a.contextArray[c].checkFramebufferStatus(b)};a.clear=function(c,b){a.contextArray[c].clear(b)};a.clearColor=function(c,b,d,f,h){a.contextArray[c].clearColor(b,d,f,h)};a.clearDepth=function(c,b){a.contextArray[c].clearDepth(b)};a.clearStencil=function(c,b){a.contextArray[c].clearStencil(b)};a.colorMask=function(c,b,d,f,h){a.contextArray[c].colorMask(b,d,f,h)};a.compileShader=function(c,b){a.contextArray[c].compileShader(a.shaderArray[b]);c=a.contextArray[c].getShaderInfoLog(a.shaderArray[b]);
console.log(c)};a.compressedTexImage2D=function(c,b,d,f,h,m,n,v){a.contextArray[c].compileShader(b,d,f,h,m,n,a.getArrayView(v))};a.compressedTexSubImage2D=function(c,b,d,f,h,m,n,v,r){a.contextArray[c].compressedTexSubImage2D(b,f,h,m,n,v,a.getArrayView(r))};a.copyTexImage2D=function(c,b,d,f,h,m,n,v,r){a.contextArray[c].copyTexImage2D(b,d,f,h,m,n,v,r)};a.copyTexSubImage2D=function(c,b,d,f,h,m,n,v,r){a.contextArray[c].copyTexSubImage2D(b,d,f,h,m,n,v,r)};a.createBuffer=function(c){var b=a.bufferArray.findIndex(function(d){return null==
d});c=a.contextArray[c].createBuffer();-1==b?(b=a.bufferArray.length,a.bufferArray.push(c)):a.bufferArray[b]=c;return b};a.createFramebuffer=function(){alert(k.callee.toString())};a.createProgram=function(c){var b=a.programArray.findIndex(function(d){return null==d});c=a.contextArray[c].createProgram();-1==b?(b=a.programArray.length,a.programArray.push(c)):a.programArray[b]=c;return b};a.createRenderbuffer=function(c){try{var b=a.renderbufferArray.findIndex(function(f){return null==f}),d=a.contextArray[c].createRenderbuffer();
-1==b?(b=a.renderbufferArray.length,a.renderbufferArray.push(d)):a.renderbufferArray[b]=d;return b}catch(f){console.log("renderBufferArray error"),console.error(f)}};a.createShader=function(c,b){var d=a.shaderArray.findIndex(function(f){return null==f});c=a.contextArray[c].createShader(b);-1==d?(d=a.shaderArray.length,a.shaderArray.push(c)):a.shaderArray[d]=c;return d};a.createTexture=function(c){var b=a.textureArray.findIndex(function(d){return null==d});c=a.contextArray[c].createTexture();-1==b?
(b=a.textureArray.length,a.textureArray.push(c)):a.textureArray[b]=c;return b};a.cullFace=function(c,b){try{a.contextArray[c].cullFace(b)}catch(d){console.log("cullFace error"),console.error(d)}};a.deleteBuffer=function(c,b){try{a.contextArray[c].deleteBuffer(a.bufferArray[b]),a.bufferArray[b]=null}catch(d){console.log("deleteBuffer error"),console.error(d)}};a.deleteFramebuffer=function(c,b){try{a.contextArray[c].deleteFramebuffer(a.framebufferArray[b]),a.framebufferArray[b]=null}catch(d){console.log("deleteFramebuffer error"),
console.error(d)}};a.deleteRenderbuffer=function(c,b){try{a.contextArray[c].deleteRenderbuffer(a.renderbufferArray[b]),a.renderbufferArray[b]=null}catch(d){console.log("deleteRenderbuffer error"),console.error(d)}};a.deleteProgram=function(c,b){try{a.contextArray[c].deleteProgram(a.programArray[b]),a.programArray[b]=null}catch(d){console.log("deleteProgram error"),console.error(d)}};a.deleteShader=function(c,b){try{a.contextArray[c].deleteShader(a.shaderArray[b]),a.shaderArray[b]=null}catch(d){console.log("deleteShader error"),
console.error(d)}};a.deleteTexture=function(c,b){try{a.contextArray[c].deleteShader(a.textureArray[b]),a.textureArray[b]=null}catch(d){console.log("deleteTexture error"),console.error(d)}};a.depthFunc=function(c,b){try{a.contextArray[c].depthFunc(b)}catch(d){console.log("depthFunc error"),console.error(d)}};a.depthMask=function(c,b){try{a.contextArray[c].depthMask(b)}catch(d){console.log("depthMask error"),console.error(d)}};a.depthRange=function(c,b,d){try{a.contextArray[c].depthRange(b,d)}catch(f){console.log("depthRange error"),
console.error(f)}};a.detachShader=function(c,b,d){try{a.contextArray[c].detachShader(b,d)}catch(f){console.log("detachShader error"),console.error(f)}};a.disable=function(c,b){try{a.contextArray[c].disable(b)}catch(d){console.log("disable error"),console.error(d)}};a.disableVertexAttribArray=function(c,b){try{a.contextArray[c].disableVertexAttribArray(b)}catch(d){console.log("disableVertexAttribArray error"),console.error(d)}};a.drawArrays=function(c,b,d,f){try{a.contextArray[c].drawArrays(b,d,f)}catch(h){console.log("drawArrays error"),
console.error(h)}};a.drawElements=function(c,b,d,f,h){try{a.contextArray[c].drawElements(b,d,f,h)}catch(m){console.log("drawElements error"),console.error(m)}};a.enable=function(c,b){try{a.contextArray[c].enable(b)}catch(d){console.log("enable error"),console.error(d)}};a.enableVertexAttribArray=function(c,b){a.contextArray[c].enableVertexAttribArray(b)};a.finish=function(c){try{a.contextArray[c].finish()}catch(b){console.log("finish error"),console.error(b)}};a.flush=function(c){try{a.contextArray[c].flush()}catch(b){console.log("flush error"),
console.error(b)}};a.framebufferRenderbuffer=function(c,b,d,f,h){try{a.contextArray[c].framebufferRenderbuffer(b,d,f,h)}catch(m){console.log("framebufferRenderbuffer error"),console.error(m)}};a.framebufferTexture2D=function(c,b,d,f,h,m){try{a.contextArray[c].framebufferTexture2D(b,d,f,h,m)}catch(n){console.log("framebufferTexture2D error"),console.error(n)}};a.frontFace=function(c,b){try{a.contextArray[c].frontFace(b)}catch(d){console.log("frontFace error"),console.error(d)}};a.generateMipmap=function(c,
b){try{a.contextArray[c].generateMipmap(b)}catch(d){console.log("generateMipmap error"),console.error(d)}};a.getActiveAttrib=function(){alert("getActiveAttrib is not implemented");return 0};a.getActiveUniform=function(){alert("getActiveUniform is not implemented");return 0};a.getAttachedShaders=function(){alert("getAttachedShaders is not implemented");return 0};a.getAttribLocation=function(c,b,d){return a.contextArray[c].getAttribLocation(a.programArray[b],a.getString(d))};a.getBufferParameter=function(c,
b,d){try{return a.contextArray[c].getBufferParameter(b,d)}catch(f){console.log("getBufferParameter error"),console.error(f)}};a.getParameter=function(c,b){try{return a.contextArray[c].getParameter(b)}catch(d){console.log("getParameter error"),console.error(d)}};a.getError=function(c){try{return a.contextArray[c].getError()}catch(b){console.log("getError error"),console.error(b)}};a.getFramebufferAttachmentParameter=function(c,b,d,f){try{return a.contextArray[c].getParameter(b,d,f)}catch(h){console.log("getFramebufferAttachmentParameter error"),
console.error(h)}};a.getProgramInfoLog=function(){alert("getProgramInfoLog not implemented");return 0};a.getRenderbufferParameter=function(c,b,d){try{return a.contextArray[c].getRenderbufferParameter(b,d)}catch(f){console.log("getRenderbufferParameter error"),console.error(f)}};a.getShaderParameter=function(){alert("getShaderParameter not implemented");return 0};a.getShaderPrecisionFormat=function(){alert("getShaderPrecisionFormat not implemented");return 0};a.getShaderInfoLog=function(){alert("getShaderInfoLog not implemented");
return 0};a.getShaderSource=function(){alert("getShaderInfoLog not implemented");return 0};a.getTexParameter=function(){alert("getTexParameter not implemented");return 0};a.getUniform=function(){alert("getUniform not implemented");return 0};a.getUniformLocation=function(c,b,d){var f=a.uniformLocationArray.findIndex(function(h){return null==h});c=a.contextArray[c].getUniformLocation(a.programArray[b],a.getString(d));-1==f?(f=a.uniformLocationArray.length,a.uniformLocationArray.push(c)):a.uniformLocationArray[f]=
c;return f};a.getVertexAttrib=function(){alert("getVertexAttrib not implemented");return 0};a.getVertexAttribOffset=function(c,b,d){try{return a.contextArray[c].getVertexAttribOffset(b,d)}catch(f){console.log("getVertexAttribOffset error"),console.error(f)}};a.hint=function(c,b,d){try{return a.contextArray[c].hint(b,d)}catch(f){console.log("hint error"),console.error(f)}};a.isBuffer=function(c,b){try{return a.contextArray[c].isBuffer(a.bufferArray[b])}catch(d){console.log("isBuffer error"),console.error(d)}};
a.isEnabled=function(c,b){try{return a.contextArray[c].isEnabled(b)}catch(d){console.log("isEnabled error"),console.error(d)}};a.isFramebuffer=function(c,b){try{return a.contextArray[c].isFramebuffer(a.framebufferArray[b])}catch(d){console.log("isFramebuffer error"),console.error(d)}};a.isProgram=function(c,b){try{return a.contextArray[c].isProgram(a.programArray[b])}catch(d){console.log("isProgram error"),console.error(d)}};a.isRenderbuffer=function(c,b){try{return a.contextArray[c].isRenderbuffer(a.renderbufferArray[b])}catch(d){console.log("isRenderbuffer error"),
console.error(d)}};a.isShader=function(c,b){try{return a.contextArray[c].isShader(a.shaderArray[b])}catch(d){console.log("isShader error"),console.error(d)}};a.isTexture=function(c,b){try{return a.contextArray[c].isTexture(a.textureArray[b])}catch(d){console.log("isTexture error"),console.error(d)}};a.lineWidth=function(c,b){try{return a.contextArray[c].lineWidth(b)}catch(d){console.log("lineWidth error"),console.error(d)}};a.linkProgram=function(c,b){a.contextArray[c].linkProgram(a.programArray[b]);
a.contextArray[c].getProgramParameter(a.programArray[b],a.contextArray[c].LINK_STATUS)||console.log(a.contextArray[c].getProgramInfoLog(a.programArray[b]))};a.pixelStorei=function(c,b,d){a.contextArray[c].pixelStorei(b,d)};a.polygonOffset=function(c,b,d){try{a.contextArray[c].polygonOffset(b,d)}catch(f){console.log("polygonOffset error"),console.error(f)}};a.readPixels=function(){alert("readPixels not implemented")};a.renderbufferStorage=function(c,b,d,f,h){try{a.contextArray[c].renderbufferStorage(b,
d,f,h)}catch(m){console.log("renderbufferStorage error"),console.error(m)}};a.sampleCoverage=function(c,b,d){try{a.contextArray[c].sampleCoverage(b,d)}catch(f){console.log("sampleCoverage error"),console.error(f)}};a.scissor=function(c,b,d,f,h){try{a.contextArray[c].scissor(b,d,f,h)}catch(m){console.log("scissor error"),console.error(m)}};a.shaderSource=function(c,b,d){a.contextArray[c].shaderSource(a.shaderArray[b],a.getString(d))};a.stencilFunc=function(c,b,d,f){try{a.contextArray[c].stencilFunc(b,
d,f)}catch(h){console.log("stencilFunc error"),console.error(h)}};a.stencilFuncSeparate=function(c,b,d,f,h){try{a.contextArray[c].stencilFuncSeparate(b,d,f,h)}catch(m){console.log("stencilFuncSeparate error"),console.error(m)}};a.stencilMask=function(c,b){try{a.contextArray[c].stencilMask(b)}catch(d){console.log("stencilMask error"),console.error(d)}};a.stencilMaskSeparate=function(c,b,d){try{a.contextArray[c].stencilMaskSeparate(b,d)}catch(f){console.log("stencilMaskSeparate error"),console.error(f)}};
a.stencilOp=function(){alert("stencilOp is not implemented")};a.stencilOpSeparate=function(){alert("stencilOpSeparate is not implemented")};a.texImage2D=function(c,b,d,f,h,m,n){a.contextArray[c].texImage2D(b,d,f,h,m,a.imageArray[n])};a.texParameterf=function(c,b,d,f){try{a.contextArray[c].texParameterf(b,d,f)}catch(h){console.log("texParameterf error"),console.error(h)}};a.texParameteri=function(c,b,d,f){a.contextArray[c].texParameteri(b,d,f)};a.texSubImage2D=function(c,b,d,f,h,m,n,v,r,t){try{a.contextArray[c].texSubImage2D(b,
d,f,h,m,n,v,r,a.getArrayView(t))}catch(D){console.log("texSubImage2D error"),console.error(D)}};a.uniform1f=function(c,b,d){try{return a.contextArray[c].uniform1f(a.uniformLocationArray[b],d)}catch(f){console.log("uniform1f error"),console.error(f)}};a.uniform1fv=function(c,b,d){try{return a.contextArray[c].uniform1fv(a.uniformLocationArray[b],a.getArrayView(d))}catch(f){console.log("uniform1fv error"),console.error(f)}};a.uniform1i=function(c,b,d){return a.contextArray[c].uniform1i(a.uniformLocationArray[b],
d)};a.uniform1iv=function(c,b,d){try{return a.contextArray[c].uniform1iv(a.uniformLocationArray[b],a.getArrayView(d))}catch(f){console.log("uniform1iv error"),console.error(f)}};a.uniform2f=function(c,b,d,f){try{return a.contextArray[c].uniform2f(a.uniformLocationArray[b],d,f)}catch(h){console.log("uniform2f error"),console.error(h)}};a.uniform2fv=function(c,b,d){try{return a.contextArray[c].uniform2fv(a.uniformLocationArray[b],a.getArrayView(d))}catch(f){console.log("uniform2fv error"),console.error(f)}};
a.uniform2i=function(c,b,d,f){try{return a.contextArray[c].uniform2i(a.uniformLocationArray[b],d,f)}catch(h){console.log("uniform2i error"),console.error(h)}};a.uniform2iv=function(c,b,d){try{return a.contextArray[c].uniform2iv(a.uniformLocationArray[b],a.getArrayView(d))}catch(f){console.log("uniform2iv error"),console.error(f)}};a.uniform3f=function(c,b,d,f,h){try{return a.contextArray[c].uniform3f(a.uniformLocationArray[b],d,f,h)}catch(m){console.log("uniform3f error"),console.error(m)}};a.uniform3fv=
function(c,b,d){try{return a.contextArray[c].uniform3fv(a.uniformLocationArray[b],new Float32Array(d))}catch(f){console.log("uniform3fv error"),console.error(f)}};a.uniform3i=function(c,b,d,f,h){try{return a.contextArray[c].uniform3i(a.uniformLocationArray[b],d,f,h)}catch(m){console.log("uniform3i error"),console.error(m)}};a.uniform3iv=function(c,b,d){try{return a.contextArray[c].uniform3iv(a.uniformLocationArray[b],a.getArrayView(d))}catch(f){console.log("uniform3iv error"),console.error(f)}};a.uniform4f=
function(c,b,d,f,h,m){try{return a.contextArray[c].uniform4f(a.uniformLocationArray[b],d,f,h,m)}catch(n){console.log("uniform4f error"),console.error(n)}};a.uniform4fv=function(c,b,d){try{return a.contextArray[c].uniform4fv(a.uniformLocationArray[b],a.getArrayView(d))}catch(f){console.log("uniform4fv error"),console.error(f)}};a.uniform4i=function(c,b,d,f,h,m){try{return a.contextArray[c].uniform4i(a.uniformLocationArray[b],d,f,h,m)}catch(n){console.log("uniform4i error"),console.error(n)}};a.uniform4iv=
function(c,b,d){try{return a.contextArray[c].uniform4iv(a.uniformLocationArray[b],a.getArrayView(d))}catch(f){console.log("uniform4iv error"),console.error(f)}};a.uniformMatrix2fv=function(c,b,d,f){try{return f>>=2,a.contextArray[c].uniformMatrix3fv(a.uniformLocationArray[b],d,(new Float32Array(a.memory.buffer)).subarray(f,f+4))}catch(h){console.log("uniformMatrix2fv error"),console.error(h)}};a.uniformMatrix3fv=function(c,b,d,f){try{return f>>=2,a.contextArray[c].uniformMatrix3fv(a.uniformLocationArray[b],
d,(new Float32Array(a.memory.buffer)).subarray(f,f+9))}catch(h){console.log("uniformMatrix3fv error"),console.error(h)}};a.uniformMatrix4fv=function(c,b,d,f){try{return f>>=2,a.contextArray[c].uniformMatrix3fv(a.uniformLocationArray[b],d,(new Float32Array(a.memory.buffer)).subarray(f,f+16))}catch(h){console.log("uniformMatrix4fv error"),console.error(h)}};a.useProgram=function(c,b){a.contextArray[c].useProgram(a.programArray[b])};a.validateProgram=function(c,b){try{a.contextArray[c].validateProgram(a.programArray[b])}catch(d){console.log("validateProgram error"),
console.error(d)}};a.vertexAttrib1f=function(c,b,d){try{return a.contextArray[c].vertexAttrib1f(b,d)}catch(f){console.log("vertexAttrib1f error"),console.error(f)}};a.vertexAttrib1fv=function(c,b,d){try{return a.contextArray[c].vertexAttrib1fv(b,a.getArrayView(d))}catch(f){console.log("vertexAttrib1fv error"),console.error(f)}};a.vertexAttrib2f=function(c,b,d,f){try{return a.contextArray[c].vertexAttrib2f(b,d,f)}catch(h){console.log("vertexAttrib2f error"),console.error(h)}};a.vertexAttrib2fv=function(c,
b,d){try{return a.contextArray[c].vertexAttrib2fv(b,a.getArrayView(d))}catch(f){console.log("vertexAttrib2fv error"),console.error(f)}};a.vertexAttrib3f=function(c,b,d,f,h){try{return a.contextArray[c].vertexAttrib3f(b,d,f,h)}catch(m){console.log("vertexAttrib3f error"),console.error(m)}};a.vertexAttrib3fv=function(c,b,d){try{return a.contextArray[c].vertexAttrib3fv(b,a.getArrayView(d))}catch(f){console.log("vertexAttrib3fv error"),console.error(f)}};a.vertexAttrib4f=function(c,b,d,f,h,m){try{return a.contextArray[c].vertexAttrib4f(b,
d,f,h,m)}catch(n){console.log("vertexAttrib4f error"),console.error(n)}};a.vertexAttrib4fv=function(c,b,d){try{return a.contextArray[c].vertexAttrib4fv(b,a.getArrayView(d))}catch(f){console.log("vertexAttrib4fv error"),console.error(f)}};a.vertexAttribPointer=function(c,b,d,f,h,m,n){a.contextArray[c].vertexAttribPointer(b,d,f,h,m,n)};a.viewport=function(c,b,d,f,h,m){try{a.contextArray[c].viewport(b,d,f,h,m)}catch(n){console.log("viewport error"),console.error(n)}};a.copyBufferSubData=function(){alert("copyBufferSubData not implemented (experimental)")};
a.getBufferSubData=function(){alert("getBufferSubData not implemented (experimental)")};a.blitFramebuffer=function(){alert("blitFramebuffer not implemented (experimental)")};a.framebufferTextureLayer=function(){alert("framebufferTextureLayer not implemented (experimental)")};a.invalidateFramebuffer=function(){alert("invalidateFramebuffer not implemented (experimental)")};a.invalidateSubFramebuffer=function(){alert("invalidateSubFramebuffer not implemented (experimental)")};a.readBuffer=function(){alert("readBuffer not implemented (experimental)")};
a.getInternalformatParameter=function(){alert("getInternalformatParameter not implemented (experimental)")};a.renderbufferStorageMultisample=function(){alert("renderbufferStorageMultisample not implemented (experimental)")};a.texStorage2D=function(){alert("texStorage2D not implemented (experimental)")};a.texStorage3D=function(){alert("texStorage3D not implemented (experimental)")};a.texSubImage3D=function(){alert("texSubImage3D not implemented (experimental)")};a.copyTexSubImage3D=function(){alert("copyTexSubImage3D not implemented (experimental)")};
a.compressedTexImage3D=function(){alert("compressedTexImage3D not implemented (experimental)")};a.compressedTexSubImage3D=function(){alert("compressedTexSubImage3D not implemented (experimental)")};a.getFragDataLocation=function(){alert("getFragDataLocation not implemented (experimental)")};a.uniform1ui=function(){alert("uniform1ui not implemented (experimental)")};a.uniform2ui=function(){alert("uniform2ui not implemented (experimental)")};a.uniform3ui=function(){alert("uniform3ui not implemented (experimental)")};
a.uniform4ui=function(){alert("uniform4ui not implemented (experimental)")};a.uniform1uiv=function(){alert("uniform1uiv not implemented (experimental)")};a.uniform2uiv=function(){alert("uniform2uiv not implemented (experimental)")};a.uniform3uiv=function(){alert("uniform3uiv not implemented (experimental)")};a.uniform4uiv=function(){alert("uniform4uiv not implemented (experimental)")};a.uniformMatrix3x2fv=function(){alert("uniformMatrix3x2fv not implemented (experimental)")};a.uniformMatrix4x2fv=
function(){alert("uniformMatrix4x2fv not implemented (experimental)")};a.uniformMatrix2x3fv=function(){alert("uniformMatrix2x3fv not implemented (experimental)")};a.uniformMatrix4x3fv=function(){alert("uniformMatrix4x3fv not implemented (experimental)")};a.uniformMatrix2x4fv=function(){console.trace("uniformMatrix2x4fv");alert("uniformMatrix2x4fv not implemented (experimental)")};a.uniformMatrix3x4fv=function(){console.trace("uniformMatrix3x4fv");alert("uniformMatrix3x4fv not implemented (experimental)")};
a.vertexAttribI4i=function(){console.trace("vertexAttribI4i");alert("vertexAttribI4i not implemented (experimental)")};a.vertexAttribI4iv=function(){console.trace("vertexAttribI4iv");alert("vertexAttribI4iv not implemented (experimental)")};a.vertexAttribI4ui=function(){console.trace("vertexAttribI4ui");alert("vertexAttribI4ui not implemented (experimental)")};a.vertexAttribI4uiv=function(){console.trace("vertexAttribI4uiv");alert("vertexAttribI4uiv not implemented (experimental)")};a.vertexAttribIPointer=
function(){console.trace("vertexAttribIPointer");alert("vertexAttribIPointer not implemented (experimental)")};a.vertexAttribDivisor=function(c,b,d){return a.contextArray[c].vertexAttribDivisor(c,b,d)};a.drawArraysInstanced=function(c,b,d,f,h){return a.contextArray[c].drawArraysInstanced(b,d,f,h)};a.drawElementsInstanced=function(c,b,d,f,h,m){try{return a.contextArray[c].drawArraysInstanced(b,d,f,h,m)}catch(n){console.log("drawElementsInstanced error"),console.error(n)}};a.drawRangeElements=function(){alert("drawRangeElements not implemented (experimental)")};
a.drawBuffers=function(){alert("drawBuffers not implemented (experimental)")};a.clearBufferfv=function(){alert("clearBufferfv not implemented (experimental)")};a.clearBufferiv=function(){alert("clearBufferiv not implemented (experimental)")};a.clearBufferuiv=function(){alert("clearBufferuiv not implemented (experimental)")};a.clearBufferfi=function(){alert("clearBufferfi not implemented (experimental)")};a.createQuery=function(){alert("createQuery not implemented (experimental)")};a.deleteQuery=function(){alert("deleteQuery not implemented (experimental)")};
a.isQuery=function(){alert("isQuery not implemented (experimental)")};a.beginQuery=function(){alert("beginQuery not implemented (experimental)")};a.endQuery=function(){alert("endQuery not implemented (experimental)")};a.getQuery=function(){alert("getQuery not implemented (experimental)")};a.getQueryParameter=function(){alert("getQueryParameter not implemented (experimental)")};a.createSampler=function(){alert("createSampler not implemented (experimental)")};a.deleteSampler=function(){alert("deleteSampler not implemented (experimental)")};
a.isSampler=function(){alert("isSampler not implemented (experimental)")};a.bindSampler=function(){alert("bindSampler not implemented (experimental)")};a.samplerParameteri=function(){alert("samplerParameteri not implemented (experimental)")};a.samplerParameterf=function(){alert("samplerParameterf not implemented (experimental)")};a.getSamplerParameter=function(){alert("getSamplerParameter not implemented (experimental)")};a.fenceSync=function(){alert("fenceSync not implemented (experimental)")};a.isSync=
function(){alert("isSync not implemented (experimental)")};a.deleteSync=function(){alert("deleteSync not implemented (experimental)")};a.clientWaitSync=function(){alert("clientWaitSync not implemented (experimental)")};a.waitSync=function(){alert("waitSync not implemented (experimental)")};a.getSyncParameter=function(){alert("getSyncParameter not implemented (experimental)")};a.createTransformFeedback=function(){alert("createTransformFeedback not implemented (experimental)")};a.deleteTransformFeedback=
function(){alert("deleteTransformFeedback not implemented (experimental)")};a.isTransformFeedback=function(){alert("isTransformFeedback not implemented (experimental)")};a.bindTransformFeedback=function(){alert("bindTransformFeedback not implemented (experimental)")};a.beginTransformFeedback=function(){alert("beginTransformFeedback not implemented (experimental)")};a.endTransformFeedback=function(){alert("endTransformFeedback not implemented (experimental)")};a.transformFeedbackVaryings=function(){alert("transformFeedbackVaryings not implemented (experimental)")};
a.getTransformFeedbackVarying=function(){alert("getTransformFeedbackVarying not implemented (experimental)")};a.pauseTransformFeedback=function(){alert("pauseTransformFeedback not implemented (experimental)")};a.resumeTransformFeedback=function(){alert("resumeTransformFeedback not implemented (experimental)")};a.bindBufferBase=function(){alert("bindBufferBase not implemented (experimental)")};a.bindBufferRange=function(){alert("bindBufferRange not implemented (experimental)")};a.getIndexedParameter=
function(){alert("getIndexedParameter not implemented (experimental)")};a.getUniformIndices=function(){alert("getUniformIndices not implemented (experimental)")};a.getActiveUniforms=function(){alert("getActiveUniforms not implemented (experimental)")};a.getUniformBlockIndex=function(){alert("getUniformBlockIndex not implemented (experimental)")};a.getActiveUniformBlockParameter=function(){alert("getActiveUniformBlockParameter not implemented (experimental)")};a.getActiveUniformBlockName=function(){alert("getActiveUniformBlockName not implemented (experimental)")};
a.uniformBlockBinding=function(){alert("uniformBlockBinding not implemented (experimental)")};a.createVertexArray=function(c){var b=a.vaoArray.findIndex(function(d){return null==d});c=a.contextArray[c].createVertexArray();-1==b?(b=a.vaoArray.length,a.vaoArray.push(c)):a.vaoArray[b]=c;return b};a.deleteVertexArray=function(){alert("deleteVertexArray not implemented (experimental)")};a.isVertexArray=function(){alert("isVertexArray not implemented (experimental)")};a.bindVertexArray=function(c,b){a.contextArray[c].bindVertexArray(a.vaoArray[b])}}
;var qa="undefined"!==typeof BigUint64Array,C=Symbol(),ra=new TextDecoder("utf-16le");function sa(e,g){var k=(new Uint32Array(e))[g+-4>>>2]>>>1;e=new Uint16Array(e,g,k);return 32>=k?String.fromCharCode.apply(String,e):ra.decode(e)}
function ta(e){function g(c,b){return c?sa(c.buffer,b):"<yet unknown>"}var k={},a=e.env=e.env||{};a.abort=a.abort||function(c,b,d,f){var h=k.memory||a.memory;throw Error("abort: "+g(h,c)+" at "+g(h,b)+":"+d+":"+f);};a.trace=a.trace||function(c,b,d){for(var f=[],h=2;h<arguments.length;++h)f[h-2]=arguments[h];console.log("trace: "+g(k.memory||a.memory,c)+(b?" ":"")+f.slice(0,b).join(", "))};a.seed=a.seed||Date.now;e.Math=e.Math||Math;e.Date=e.Date||Date;return k}
function E(){throw Error("Operation requires compiling with --exportRuntime");}
function ua(e,g){function k(l){var q=l;var p=new Uint32Array(h.buffer),u=p[D>>>2];if((q>>>=0)>=u)throw Error("invalid id: "+q);q=p[(D+4>>>2)+2*q];if(!(q&7))throw Error("not an array: "+l+", flags="+q);return q}function a(l,q,p){var u=h.buffer;if(p)switch(l){case 2:return new Float32Array(u);case 3:return new Float64Array(u)}else switch(l){case 0:return new (q?Int8Array:Uint8Array)(u);case 1:return new (q?Int16Array:Uint16Array)(u);case 2:return new (q?Int32Array:Uint32Array)(u);case 3:return new (q?
BigInt64Array:BigUint64Array)(u)}throw Error("unsupported align: "+l);}function c(l){var q=new Uint32Array(h.buffer),p=k(q[l+-8>>>2]),u=31-Math.clz32(p>>>6&31),x=p&4?l:q[l+4>>>2];l=p&2?q[l+12>>>2]:q[x+-4>>>2]>>>u;return a(u,p&2048,p&4096).subarray(x>>>=u,x+l)}function b(l,q,p){return new l(d(l,q,p))}function d(l,q,p){var u=h.buffer,x=new Uint32Array(u);p=x[p+4>>>2];return new l(u,p,x[p+-4>>>2]>>>q)}function f(l,q,p){e["__get"+q]=b.bind(null,l,p);e["__get"+q+"View"]=d.bind(null,l,p)}g=g.exports;var h=
g.memory,m=g.table,n=g.__new||E,v=g.__pin||E,r=g.__unpin||E,t=g.__collect||E,D=g.__rtti_base||-1;e.__new=n;e.__pin=v;e.__unpin=r;e.__collect=t;e.__newString=function(l){if(null==l)return 0;for(var q=l.length,p=n(q<<1,1),u=new Uint16Array(h.buffer),x=0,H=p>>>1;x<q;++x)u[H+x]=l.charCodeAt(x);return p};e.__getString=function(l){if(!l)return null;var q=h.buffer;if(1!==(new Uint32Array(q))[l+-8>>>2])throw Error("not a string: "+l);return sa(q,l)};e.__newArray=function(l,q){var p=k(l),u=31-Math.clz32(p>>>
6&31),x=q.length,H=n(x<<u,p&4?l:0);if(p&4)l=H;else{v(H);l=n(p&2?16:12,l);r(H);var K=new Uint32Array(h.buffer);K[l+0>>>2]=H;K[l+4>>>2]=H;K[l+8>>>2]=x<<u;p&2&&(K[l+12>>>2]=x)}K=a(u,p&2048,p&4096);if(p&16384)for(p=0;p<x;++p)K[(H>>>u)+p]=q[p];else K.set(q,H>>>u);return l};e.__getArrayView=c;e.__getArray=function(l){l=c(l);for(var q=l.length,p=Array(q),u=0;u<q;u++)p[u]=l[u];return p};e.__getArrayBuffer=function(l){var q=h.buffer,p=(new Uint32Array(q))[l+-4>>>2];return q.slice(l,l+p)};[Int8Array,Uint8Array,
Uint8ClampedArray,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array].forEach(function(l){f(l,l.name,31-Math.clz32(l.BYTES_PER_ELEMENT))});qa&&[BigUint64Array,BigInt64Array].forEach(function(l){f(l,l.name.slice(3),3)});e.__instanceof=function(l,q){var p=new Uint32Array(h.buffer);l=p[l+-8>>>2];if(l<=p[D>>>2]){do{if(l==q)return!0;p=l;l=new Uint32Array(h.buffer);var u=l[D>>>2];if((p>>>=0)>=u)throw Error("invalid id: "+p);l=l[(D+4>>>2)+2*p+1]}while(l)}return!1};e.memory=e.memory||
h;e.table=e.table||m;return va(g,e)}function wa(e){return"undefined"!==typeof Response&&e instanceof Response}
function xa(e,g){g=void 0===g?{}:g;var k,a,c,b,d,f;return na(function(h){switch(h.g){case 1:return k=wa,A(h,e,2);case 2:if(k(e=h.i))return h.return(ya(e,g));if(e instanceof WebAssembly.Module){a=e;h.g=3;break}return A(h,WebAssembly.compile(e),4);case 4:a=h.i;case 3:return c=a,b=ta(g),A(h,WebAssembly.instantiate(c,g),5);case 5:return d=h.i,f=ua(b,d),h.return({module:c,instance:d,exports:f})}})}
function ya(e,g){g=void 0===g?{}:g;var k,a,c,b,d;return na(function(f){switch(f.g){case 1:if(WebAssembly.instantiateStreaming){f.g=2;break}k=xa;a=wa;return A(f,e,3);case 3:return f.return(k(a(e=f.i)?e.arrayBuffer():e,g));case 2:return c=ta(g),A(f,WebAssembly.instantiateStreaming(e,g),4);case 4:return b=f.i,d=ua(c,b.instance),f.return(Object.assign({},b,{exports:d}))}})}
function va(e,g){g=void 0===g?{}:g;var k=e.__argumentsLength?function(n){e.__argumentsLength.value=n}:e.__setArgumentsLength||e.__setargc||function(){},a={},c;for(c in e){if(Object.prototype.hasOwnProperty.call(e,c)){a.j=e[c];for(var b=c.split("."),d=g;1<b.length;){var f=b.shift();Object.prototype.hasOwnProperty.call(d,f)||(d[f]={});d=d[f]}b=b[0];f=b.indexOf("#");if(0<=f){var h=b.substring(0,f);a.s=d[h];"undefined"!==typeof a.s&&a.s.prototype||(a.o=function(n){return function(v){for(var r=[],t=0;t<
arguments.length;++t)r[t]=arguments[t];return n.o.P(n.o.prototype.constructor.apply(n.o.prototype,[0].concat(w(r))))}}(a),a.o.prototype={valueOf:function(){return this[C]}},a.o.P=function(n){return function(v){var r={};return Object.create(n.o.prototype,(r[C]={value:v,writable:!1},r))}}(a),a.s&&Object.getOwnPropertyNames(a.s).forEach(function(n){return function(v){return Object.defineProperty(n.o,v,Object.getOwnPropertyDescriptor(n.s,v))}}(a)),d[h]=a.o);b=b.substring(f+1);d=d[h].prototype;if(/^(get|set):/.test(b))Object.prototype.hasOwnProperty.call(d,
b=b.substring(4))||(a.B=e[c.replace("set:","get:")],a.C=e[c.replace("get:","set:")],Object.defineProperty(d,b,{get:function(n){return function(){return n.B(this[C])}}(a),set:function(n){return function(v){n.C(this[C],v)}}(a),enumerable:!0}));else if("constructor"===b)(d[b]=function(n){return function(v){for(var r=[],t=0;t<arguments.length;++t)r[t]=arguments[t];k(r.length);return n.j.apply(null,w(r))}}(a)).D=a.j;else{var m=this;(d[b]=function(n){return function(v){for(var r=[],t=0;t<arguments.length;++t)r[t]=
arguments[t];k(r.length);return n.j.apply(null,[m[C]].concat(w(r)))}}(a)).D=a.j}}else/^(get|set):/.test(b)?Object.prototype.hasOwnProperty.call(d,b=b.substring(4))||Object.defineProperty(d,b,{get:e[c.replace("set:","get:")],set:e[c.replace("get:","set:")],enumerable:!0}):"function"===typeof a.j&&a.j!==k?(d[b]=function(n){return function(v){for(var r=[],t=0;t<arguments.length;++t)r[t]=arguments[t];k(r.length);return n.j.apply(null,w(r))}}(a)).D=a.j:d[b]=a.j}a={o:a.o,s:a.s,B:a.B,C:a.C,j:a.j}}return g}
;var za=Math.random().toString(36).substr(2,9),Aa,F,G=document.getElementById("cnvs"),Ba=new Audio("audio/replica.mp3"),Ca=new Audio("audio/deadly_slot_game.mp3"),Da=new Audio("audio/aesir_chaos.mp3"),Ea=new Audio("audio/laserSmall_000.ogg"),Fa=new Audio("audio/explosion-hq.mp3"),I="chill",J={chill:Ba,fight1:Ca,fight2:Da},Ga={laser:Ea,explosion:Fa},L=null,M=null,N=null,O=null,P=0,Q=null,R=null,S=100;function Ha(){null!=O&&(O.close(),O=null)}
function Ia(){function e(){Q=setTimeout(function(){F.SendTimeSync();e()},S+(20*Math.random()-10));S*=2;1E3<S&&(S=1E3)}F.OnConnectionOpen(performance.now());S=100;e();R=setInterval(function(){F.OnReliableSendTimer()},100)}function Ja(){null!=Q&&(clearTimeout(Q),Q=null);null!=R&&(clearInterval(R),R=null);null!=M&&(M.close(),M=null);null!=N&&(N.close(),N=null);null!=L&&(L.close(),L=null);P=0}
function Ka(e){null!=L?console.error("StartRTCPeerConnection: webrtc_conn not null"):(L=new RTCPeerConnection(null),M=L.createDataChannel("unreliable",{ordered:!1,maxPacketLifeTime:100}),M.onopen=function(){P++;2<=P&&F.OnConnectionOpen(performance.now())},M.onerror=function(g){console.log("onerror:",M.readyState,g)},M.onclose=function(){F.OnConnectionClose();Ha();Ja()},M.onmessage=function(g){var k=performance.now();g=F.__pin(F.__newArray(F.UINT8ARRAY_ID,new Uint8Array(g.data)));F.OnConnectionUnreliableData(k,
g);F.__unpin(g)},M.onbufferedamountlow=function(){},N=L.createDataChannel("reliable",{ordered:!0,maxRetransmits:1E3}),N.onopen=function(){P++;2<=P&&Ia()},N.onerror=function(g){console.log("onerror:",N.readyState,g)},N.onclose=function(){F.OnConnectionClose();Ha();Ja()},N.onmessage=function(g){g=F.__pin(F.__newArray(F.UINT8ARRAY_ID,new Uint8Array(g.data)));F.OnConnectionReliableData(g);F.__unpin(g)},N.onbufferedamountlow=function(){},L.createOffer().then(function(g){return L.setLocalDescription(g)}).then(function(){e(L.localDescription)}).catch(function(g){console.error("createOffer failed: "+
g);Ha();Ja()}))}
function La(){O=new WebSocket("wss://"+location.hostname+":8443/bb/"+za);O.onopen=function(){console.log("WebSocket client connected");L||Ka(function(e){null!=O?O.send(JSON.stringify({type:"offer",offer:e})):Ja()})};O.onclose=function(){console.error("WebSocket client disconnected");O=null;setTimeout(function(){location.reload()},3E3);setTimeout(function(){La()},1E3)};O.onerror=function(e){console.error("WebSocket error",e)};O.onmessage=function(e){try{var g=JSON.parse(e.data);"answer"==g.type&&null!=
L?L.setRemoteDescription(new RTCSessionDescription({type:"answer",sdp:g.sdp})):"candidate"==g.type&&null!=L&&L.addIceCandidate(new RTCIceCandidate({candidate:g.candidate,sdpMid:g.mid}))}catch(k){console.error("Websocket message parse failed: err=",k)}}}var T=!1,Ma=0,Na=0,U=0,V=0,W=!1;
function Oa(){T||(T=!0,document.body.style.backgroundColor="#444",Ma=parseInt(window.getComputedStyle(G.parentNode).getPropertyValue("margin-left"),10),Na=parseInt(window.getComputedStyle(G.parentNode).getPropertyValue("margin-top"),10),W&&(J[I].play(),J[I].loop=!0))}function Pa(){T&&(T=!1,V=U=-1,document.body.style.backgroundColor="white",W&&J[I].pause())}
function Qa(e){e.touches?(U=e.targetTouches[0].clientX-Ma,V=e.targetTouches[0].clientY-Na):e.offsetX?(U=e.offsetX,V=e.offsetY):e.layerX&&(U=e.layerX,V=e.layerY)}G.addEventListener("touchmove",function(e){e.preventDefault();Qa(e)},{passive:!1});G.addEventListener("MozTouchMove",function(e){e.preventDefault();Qa(e)},{passive:!1});G.addEventListener("mousemove",function(e){Qa(e)},{passive:!0});G.addEventListener("touchstart",function(e){e.preventDefault();Oa()},{passive:!1});
G.addEventListener("MozTouchDown",function(e){e.preventDefault();Oa()},{passive:!1});G.addEventListener("mouseover",function(){Oa()},{passive:!0});G.addEventListener("touchend",function(e){e.preventDefault();Pa()},{passive:!1});G.addEventListener("MozTouchUp",function(e){e.preventDefault();Pa()},{passive:!1});G.addEventListener("mouseout",function(){Pa()},{passive:!0});document.addEventListener("mousedown",function(){W||(W=!0,J[I].play(),J[I].loop=!0)},{passive:!0});var Ra=0,Sa=0,X=0,Y=0,Ta=0;
function Ua(){(window.innerWidth!=Ra||window.innerHeight!=Sa)&&100<=performance.now()-Ta&&(Ra=window.innerWidth,Sa=window.innerHeight,X=.98*Ra-32,Y=.98*Sa-32,X>Y?X=Y:Y=X,G.width=X,G.height=X,G.style.width=X+"px",G.style.height=X+"px",Ta=performance.now());F.RenderFrame(performance.now(),U,V,X,Y);requestAnimationFrame(Ua)}var Z={netcode:{}};Z.netcode.consoleLog=function(e){var g=F.__getString(e);setTimeout(function(){console.log(g)},50)};Z.netcode.getMilliseconds=function(){return performance.now()};
Z.client={};Z.client.sendReliable=function(e){null!=N&&N.send(F.__getUint8ArrayView(e))};Z.client.sendUnreliable=function(e){null!=M&&M.send(F.__getUint8ArrayView(e))};
Z.client.playMusic=function(e){var g=F.__getString(e);setTimeout(function(){if(I!=g){var k=I,a=function(){var d=J[k].volume-.1;0>=d?J[k].pause():(J[k].volume=d,setTimeout(a,100))};a()}I=g;if(W){var c=I;J[c].volume=.1;T&&J[c].play();var b=function(){var d=J[c].volume+.1;1>d?(J[c].volume=d,setTimeout(b,100)):J[c].volume=1};b();J[I].loop=!0}},0)};Z.client.playSFX=function(e){var g=F.__getString(e);setTimeout(function(){W&&(Ga[g].pause(),Ga[g].play())},0)};Z.client.serverLoginGood=function(){console.log("LoginGood")};
Z.client.serverLoginBad=function(e){e=F.__getString(e);console.error("LoginBad:",e)};Z.env={};
(function(e){var g=new WebAssembly.Memory({initial:1E4}),k=Object.assign({},Z);k.env.memory=g;pa(k);(function(){var a;return na(function(c){if(1==c.g)return A(c,fetch(e),2);a=c.i;ya(a,k).then(function(b){Aa=b;F=Aa.exports;console.log("ASWebGLReady");null==b?console.error("ASWebGLReady requires the WebAssembly Instance as 1st parameter"):null==b?console.error("ASWebGLReady requires import object as 2nd parameter"):(k.WebGL.WEBGL_READY=!0,console.log("========================="),console.log(b.instance.exports),
console.log(b.instance.exports.__rtti_base),k.WebGL.RTTI_BASE=b.instance.exports.__rtti_base);F.Initialize();La();requestAnimationFrame(Ua)});c.g=0})})()})("client.wasm");
