function aa(a){var g=0;return function(){return g<a.length?{done:!1,value:a[g++]}:{done:!0}}}function ba(a){var g="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return g?g.call(a):{next:aa(a)}}function w(a){if(!(a instanceof Array)){a=ba(a);for(var g,k=[];!(g=a.next()).done;)k.push(g.value);a=k}return a}var ca="function"==typeof Object.defineProperties?Object.defineProperty:function(a,g,k){if(a==Array.prototype||a==Object.prototype)return a;a[g]=k.value;return a};
function da(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var g=0;g<a.length;++g){var k=a[g];if(k&&k.Math==Math)return k}throw Error("Cannot find global object");}var y=da(this);function z(a,g){if(g)a:{var k=y;a=a.split(".");for(var c=0;c<a.length-1;c++){var d=a[c];if(!(d in k))break a;k=k[d]}a=a[a.length-1];c=k[a];g=g(c);g!=c&&null!=g&&ca(k,a,{configurable:!0,writable:!0,value:g})}}
function ea(){this.v=!1;this.j=null;this.l=void 0;this.h=1;this.K=0;this.u=null}function fa(a){if(a.v)throw new TypeError("Generator is already running");a.v=!0}ea.prototype.I=function(a){this.l=a};function ha(a,g){a.u={sa:g,va:!0};a.h=a.K}ea.prototype.return=function(a){this.u={return:a};this.h=this.K};function A(a,g,k){a.h=k;return{value:g}}function ia(a){this.h=new ea;this.j=a}
function ja(a,g){fa(a.h);var k=a.h.j;if(k)return ka(a,"return"in k?k["return"]:function(c){return{value:c,done:!0}},g,a.h.return);a.h.return(g);return B(a)}function ka(a,g,k,c){try{var d=g.call(a.h.j,k);if(!(d instanceof Object))throw new TypeError("Iterator result "+d+" is not an object");if(!d.done)return a.h.v=!1,d;var b=d.value}catch(e){return a.h.j=null,ha(a.h,e),B(a)}a.h.j=null;c.call(a.h,b);return B(a)}
function B(a){for(;a.h.h;)try{var g=a.j(a.h);if(g)return a.h.v=!1,{value:g.value,done:!1}}catch(k){a.h.l=void 0,ha(a.h,k)}a.h.v=!1;if(a.h.u){g=a.h.u;a.h.u=null;if(g.va)throw g.sa;return{value:g.return,done:!0}}return{value:void 0,done:!0}}
function la(a){this.next=function(g){fa(a.h);a.h.j?g=ka(a,a.h.j.next,g,a.h.I):(a.h.I(g),g=B(a));return g};this.throw=function(g){fa(a.h);a.h.j?g=ka(a,a.h.j["throw"],g,a.h.I):(ha(a.h,g),g=B(a));return g};this.return=function(g){return ja(a,g)};this[Symbol.iterator]=function(){return this}}function ma(a){function g(c){return a.next(c)}function k(c){return a.throw(c)}return new Promise(function(c,d){function b(e){e.done?c(e.value):Promise.resolve(e.value).then(g,k).then(b,d)}b(a.next())})}
function na(a){return ma(new la(new ia(a)))}z("Symbol",function(a){function g(b){if(this instanceof g)throw new TypeError("Symbol is not a constructor");return new k(c+(b||"")+"_"+d++,b)}function k(b,e){this.h=b;ca(this,"description",{configurable:!0,writable:!0,value:e})}if(a)return a;k.prototype.toString=function(){return this.h};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",d=0;return g});
z("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var g="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),k=0;k<g.length;k++){var c=y[g[k]];"function"===typeof c&&"function"!=typeof c.prototype[a]&&ca(c.prototype,a,{configurable:!0,writable:!0,value:function(){return oa(aa(this))}})}return a});function oa(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
z("Promise",function(a){function g(e){this.j=0;this.l=void 0;this.h=[];this.K=!1;var f=this.u();try{e(f.resolve,f.reject)}catch(h){f.reject(h)}}function k(){this.h=null}function c(e){return e instanceof g?e:new g(function(f){f(e)})}if(a)return a;k.prototype.j=function(e){if(null==this.h){this.h=[];var f=this;this.l(function(){f.v()})}this.h.push(e)};var d=y.setTimeout;k.prototype.l=function(e){d(e,0)};k.prototype.v=function(){for(;this.h&&this.h.length;){var e=this.h;this.h=[];for(var f=0;f<e.length;++f){var h=
e[f];e[f]=null;try{h()}catch(m){this.u(m)}}}this.h=null};k.prototype.u=function(e){this.l(function(){throw e;})};g.prototype.u=function(){function e(m){return function(n){h||(h=!0,m.call(f,n))}}var f=this,h=!1;return{resolve:e(this.ea),reject:e(this.v)}};g.prototype.ea=function(e){if(e===this)this.v(new TypeError("A Promise cannot resolve to itself"));else if(e instanceof g)this.ga(e);else{a:switch(typeof e){case "object":var f=null!=e;break a;case "function":f=!0;break a;default:f=!1}f?this.ba(e):
this.I(e)}};g.prototype.ba=function(e){var f=void 0;try{f=e.then}catch(h){this.v(h);return}"function"==typeof f?this.ha(f,e):this.I(e)};g.prototype.v=function(e){this.aa(2,e)};g.prototype.I=function(e){this.aa(1,e)};g.prototype.aa=function(e,f){if(0!=this.j)throw Error("Cannot settle("+e+", "+f+"): Promise already settled in state"+this.j);this.j=e;this.l=f;2===this.j&&this.fa();this.xa()};g.prototype.fa=function(){var e=this;d(function(){if(e.ya()){var f=y.console;"undefined"!==typeof f&&f.error(e.l)}},
1)};g.prototype.ya=function(){if(this.K)return!1;var e=y.CustomEvent,f=y.Event,h=y.dispatchEvent;if("undefined"===typeof h)return!0;"function"===typeof e?e=new e("unhandledrejection",{cancelable:!0}):"function"===typeof f?e=new f("unhandledrejection",{cancelable:!0}):(e=y.document.createEvent("CustomEvent"),e.initCustomEvent("unhandledrejection",!1,!0,e));e.promise=this;e.reason=this.l;return h(e)};g.prototype.xa=function(){if(null!=this.h){for(var e=0;e<this.h.length;++e)b.j(this.h[e]);this.h=null}};
var b=new k;g.prototype.ga=function(e){var f=this.u();e.N(f.resolve,f.reject)};g.prototype.ha=function(e,f){var h=this.u();try{e.call(f,h.resolve,h.reject)}catch(m){h.reject(m)}};g.prototype.then=function(e,f){function h(r,t){return"function"==typeof r?function(D){try{m(r(D))}catch(l){n(l)}}:t}var m,n,v=new g(function(r,t){m=r;n=t});this.N(h(e,m),h(f,n));return v};g.prototype.catch=function(e){return this.then(void 0,e)};g.prototype.N=function(e,f){function h(){switch(m.j){case 1:e(m.l);break;case 2:f(m.l);
break;default:throw Error("Unexpected state: "+m.j);}}var m=this;null==this.h?b.j(h):this.h.push(h);this.K=!0};g.resolve=c;g.reject=function(e){return new g(function(f,h){h(e)})};g.race=function(e){return new g(function(f,h){for(var m=ba(e),n=m.next();!n.done;n=m.next())c(n.value).N(f,h)})};g.all=function(e){var f=ba(e),h=f.next();return h.done?c([]):new g(function(m,n){function v(D){return function(l){r[D]=l;t--;0==t&&m(r)}}var r=[],t=0;do r.push(void 0),t++,c(h.value).N(v(r.length-1),n),h=f.next();
while(!h.done)})};return g});z("Math.clz32",function(a){return a?a:function(g){g=Number(g)>>>0;if(0===g)return 32;var k=0;0===(g&4294901760)&&(g<<=16,k+=16);0===(g&4278190080)&&(g<<=8,k+=8);0===(g&4026531840)&&(g<<=4,k+=4);0===(g&3221225472)&&(g<<=2,k+=2);0===(g&2147483648)&&k++;return k}});z("Array.prototype.findIndex",function(a){return a?a:function(g,k){a:{var c=this;c instanceof String&&(c=String(c));for(var d=c.length,b=0;b<d;b++)if(g.call(k,c[b],b,c)){g=b;break a}g=-1}return g}});
function pa(a){function g(d,b,e,f){c.g[d].bufferData(b,c.m(e),f)}var k=arguments;null==a.env.memory&&alert("You need to set memory in your importObject");null==a.WebGL&&(a.WebGL={});var c=a.WebGL;a.env.abort=function(d){for(var b=[],e=0;e<arguments.length;++e)b[e]=arguments[e];console.log("abort");console.log(c.C(b[0]))};a.WebGL.na=!1;a.WebGL.memory=a.env.memory;a.WebGL.g=[];a.WebGL.F=[];a.WebGL.J=[];a.WebGL.o=[];a.WebGL.A=[];a.WebGL.D=[];a.WebGL.ta=[];a.WebGL.H=[];a.WebGL.i=[];a.WebGL.L=[];a.WebGL.la=
-4;a.WebGL.ia=-8;a.WebGL.Ba=1024;a.WebGL.Sa=1;a.WebGL.S=0;a.WebGL.X=6;a.ca=4;a.da=12;a.WebGL.NONE=0;a.WebGL.W=1;a.WebGL.R=2;a.WebGL.T=4;a.WebGL.Ra=8;a.WebGL.Ma=16;a.WebGL.Aa=32;a.WebGL.Ua=64;a.WebGL.Va=128;a.WebGL.Wa=256;a.WebGL.Xa=512;a.WebGL.Ya=1024;a.WebGL.bb=2048;a.WebGL.Za=4096;a.WebGL.ab=8192;a.WebGL.$a=16384;a.WebGL.Da=32768;a.WebGL.Ea=65536;a.WebGL.Fa=131072;a.WebGL.Ga=262144;a.WebGL.Ha=524288;a.WebGL.La=1048576;a.WebGL.Ia=2097152;a.WebGL.Ka=4194304;a.WebGL.Ja=8388608;a.WebGL.mb=function(d){console.log("createImage("+
d+")");var b=new Image;b.ready=!1;b.onload=function(){b.ready=!0};b.src=c.C(d);console.log("image.src="+b.src);d=c.J.length;c.J.push(b);return d};a.WebGL.sb=function(d){console.log("logi32="+d)};a.WebGL.rb=function(d){console.log("logf32="+d)};a.WebGL.qb=function(d){return c.J.length<=d?!1:c.J[d].ready};a.WebGL.ua=function(d,b,e){var f=c.memory.buffer;if(e)switch(d){case 2:return new Float32Array(f);case 3:return new Float64Array(f)}else switch(d){case 0:return new (b?Int8Array:Uint8Array)(f);case 1:return new (b?
Int16Array:Uint16Array)(f);case 2:return new (b?Int32Array:Uint32Array)(f);case 3:return new (b?BigInt64Array:BigUint64Array)(f)}throw Error("unsupported align: "+d);};a.WebGL.nb=function(d){var b=c.ob(d);if(!(b&(c.W|c.R|c.T)))throw Error("not an array: "+d+", flags="+b);return b};a.WebGL.pb=function(d){return 31-Math.clz32(d>>>c.X&31)};a.WebGL.m=function(d){var b=new Uint32Array(c.memory.buffer),e=b[d+c.ia>>>2];if(e>=b[c.S>>>2])throw Error("invalid id: "+e);var f=b[(c.S+4>>>2)+2*e];if(!(f&(c.W|c.R|
c.T)))throw Error("not an array: "+e+", flags="+f);e=31-Math.clz32(f>>>c.X&31);var h=f&c.T?d:b[d+c.ca>>>2];d=f&c.R?b[d+c.da>>>2]:b[h+c.la>>>2]>>>e;return c.ua(e,f&c.eb,f&c.cb).subarray(h>>>=e,h+d)};a.WebGL.C=function(d){var b=c.memory.buffer,e=new Uint32Array(b),f=d/4-2,h=e[f];if(1!==h)throw Error("not a string index="+d+" id="+h);e=e[f+1];return(new TextDecoder("utf-16")).decode(b.slice(d,d+e))};a.WebGL.lb=function(d,b){d=document.getElementById(c.C(d)).getContext(c.C(b),{alpha:!1});b=c.g.findIndex(function(e){return null==
e});-1==b?(b=c.g.length,c.g.push(d)):c.g[b]=d;return b};a.WebGL.getSupportedExtensions=function(){alert("getSupportedExtensions is not currently supported")};a.WebGL.getExtension=function(d,b){c.g[d].getExtension(c.C(b))};a.WebGL.activeTexture=function(d,b){c.g[d].activeTexture(b)};a.WebGL.attachShader=function(d,b,e){c.g[d].attachShader(c.o[b],c.A[e])};a.WebGL.bindAttribLocation=function(d,b,e,f){c.g[d].bindAttribLocation(c.o[b],e,c.C(f))};a.WebGL.bindBuffer=function(d,b,e){c.g[d].bindBuffer(b,c.D[e])};
a.WebGL.bindFramebuffer=function(d,b,e){c.g[d].bindFramebuffer(b,c.Z[e])};a.WebGL.bindRenderbuffer=function(d,b,e){c.g[d].bindRenderbuffer(b,c.vb[e])};a.WebGL.bindTexture=function(d,b,e){c.g[d].bindTexture(b,c.F[e])};a.WebGL.blendColor=function(d,b,e,f,h){c.g[d].blendColor(b,e,f,h)};a.WebGL.blendEquation=function(d,b){c.g[d].blendEquation(b)};a.WebGL.blendEquationSeparate=function(d,b,e){c.g[d].blendEquationSeparate(b,e)};a.WebGL.blendFunc=function(d,b,e){c.g[d].blendFunc(b,e)};a.WebGL.blendFuncSeparate=
function(d,b,e,f,h){c.g[d].blendFuncSeparate(b,e,f,h)};a.WebGL["bufferData<f32>"]=g;a.WebGL["bufferData<f64>"]=g;a.WebGL["bufferData<i32>"]=g;a.WebGL["bufferData<u16>"]=g;a.WebGL["bufferData<u8>"]=g;a.WebGL.bufferSubData=function(d,b,e,f,h,m){c.g[d].bufferSubData(b,e,c.m(f),h,m)};a.WebGL.checkFramebufferStatus=function(d,b){return c.g[d].checkFramebufferStatus(b)};a.WebGL.clear=function(d,b){c.g[d].clear(b)};a.WebGL.clearColor=function(d,b,e,f,h){c.g[d].clearColor(b,e,f,h)};a.WebGL.clearDepth=function(d,
b){c.g[d].clearDepth(b)};a.WebGL.clearStencil=function(d,b){c.g[d].clearStencil(b)};a.WebGL.colorMask=function(d,b,e,f,h){c.g[d].colorMask(b,e,f,h)};a.WebGL.compileShader=function(d,b){c.g[d].compileShader(c.A[b]);d=c.g[d].getShaderInfoLog(c.A[b]);console.log(d)};a.WebGL.compressedTexImage2D=function(d,b,e,f,h,m,n,v){c.g[d].compileShader(b,e,f,h,m,n,c.m(v))};a.WebGL.compressedTexSubImage2D=function(d,b,e,f,h,m,n,v,r){c.g[d].compressedTexSubImage2D(b,f,h,m,n,v,c.m(r))};a.WebGL.copyTexImage2D=function(d,
b,e,f,h,m,n,v,r){c.g[d].copyTexImage2D(b,e,f,h,m,n,v,r)};a.WebGL.copyTexSubImage2D=function(d,b,e,f,h,m,n,v,r){c.g[d].copyTexSubImage2D(b,e,f,h,m,n,v,r)};a.WebGL.createBuffer=function(d){var b=c.D.findIndex(function(e){return null==e});d=c.g[d].createBuffer();-1==b?(b=c.D.length,c.D.push(d)):c.D[b]=d;return b};a.WebGL.createFramebuffer=function(){alert(k.callee.toString())};a.WebGL.createProgram=function(d){var b=c.o.findIndex(function(e){return null==e});d=c.g[d].createProgram();-1==b?(b=c.o.length,
c.o.push(d)):c.o[b]=d;return b};a.WebGL.createRenderbuffer=function(d){try{var b=c.H.findIndex(function(f){return null==f}),e=c.g[d].createRenderbuffer();-1==b?(b=c.H.length,c.H.push(e)):c.H[b]=e;return b}catch(f){console.log("renderBufferArray error"),console.error(f)}};a.WebGL.createShader=function(d,b){var e=c.A.findIndex(function(f){return null==f});d=c.g[d].createShader(b);-1==e?(e=c.A.length,c.A.push(d)):c.A[e]=d;return e};a.WebGL.createTexture=function(d){var b=c.F.findIndex(function(e){return null==
e});d=c.g[d].createTexture();-1==b?(b=c.F.length,c.F.push(d)):c.F[b]=d;return b};a.WebGL.cullFace=function(d,b){try{c.g[d].cullFace(b)}catch(e){console.log("cullFace error"),console.error(e)}};a.WebGL.deleteBuffer=function(d,b){try{c.g[d].deleteBuffer(c.D[b]),c.D[b]=null}catch(e){console.log("deleteBuffer error"),console.error(e)}};a.WebGL.deleteFramebuffer=function(d,b){try{c.g[d].deleteFramebuffer(c.Z[b]),c.Z[b]=null}catch(e){console.log("deleteFramebuffer error"),console.error(e)}};a.WebGL.deleteRenderbuffer=
function(d,b){try{c.g[d].deleteRenderbuffer(c.H[b]),c.H[b]=null}catch(e){console.log("deleteRenderbuffer error"),console.error(e)}};a.WebGL.deleteProgram=function(d,b){try{c.g[d].deleteProgram(c.o[b]),c.ub[b]=null}catch(e){console.log("deleteProgram error"),console.error(e)}};a.WebGL.deleteShader=function(d,b){try{c.g[d].deleteShader(c.A[b]),c.A[b]=null}catch(e){console.log("deleteShader error"),console.error(e)}};a.WebGL.deleteTexture=function(d,b){try{c.g[d].deleteShader(c.F[b]),c.F[b]=null}catch(e){console.log("deleteTexture error"),
console.error(e)}};a.WebGL.depthFunc=function(d,b){try{c.g[d].depthFunc(b)}catch(e){console.log("depthFunc error"),console.error(e)}};a.WebGL.depthMask=function(d,b){try{c.g[d].depthMask(b)}catch(e){console.log("depthMask error"),console.error(e)}};a.WebGL.depthRange=function(d,b,e){try{c.g[d].depthRange(b,e)}catch(f){console.log("depthRange error"),console.error(f)}};a.WebGL.detachShader=function(d,b,e){try{c.g[d].detachShader(b,e)}catch(f){console.log("detachShader error"),console.error(f)}};a.WebGL.disable=
function(d,b){try{c.g[d].disable(b)}catch(e){console.log("disable error"),console.error(e)}};a.WebGL.disableVertexAttribArray=function(d,b){try{c.g[d].disableVertexAttribArray(b)}catch(e){console.log("disableVertexAttribArray error"),console.error(e)}};a.WebGL.drawArrays=function(d,b,e,f){try{c.g[d].drawArrays(b,e,f)}catch(h){console.log("drawArrays error"),console.error(h)}};a.WebGL.drawElements=function(d,b,e,f,h){try{c.g[d].drawElements(b,e,f,h)}catch(m){console.log("drawElements error"),console.error(m)}};
a.WebGL.enable=function(d,b){try{c.g[d].enable(b)}catch(e){console.log("enable error"),console.error(e)}};a.WebGL.enableVertexAttribArray=function(d,b){c.g[d].enableVertexAttribArray(b)};a.WebGL.finish=function(d){try{c.g[d].finish()}catch(b){console.log("finish error"),console.error(b)}};a.WebGL.flush=function(d){try{c.g[d].flush()}catch(b){console.log("flush error"),console.error(b)}};a.WebGL.framebufferRenderbuffer=function(d,b,e,f,h){try{c.g[d].framebufferRenderbuffer(b,e,f,h)}catch(m){console.log("framebufferRenderbuffer error"),
console.error(m)}};a.WebGL.framebufferTexture2D=function(d,b,e,f,h,m){try{c.g[d].framebufferTexture2D(b,e,f,h,m)}catch(n){console.log("framebufferTexture2D error"),console.error(n)}};a.WebGL.frontFace=function(d,b){try{c.g[d].frontFace(b)}catch(e){console.log("frontFace error"),console.error(e)}};a.WebGL.generateMipmap=function(d,b){try{c.g[d].generateMipmap(b)}catch(e){console.log("generateMipmap error"),console.error(e)}};a.WebGL.getActiveAttrib=function(){alert("getActiveAttrib is not implemented");
return 0};a.WebGL.getActiveUniform=function(){alert("getActiveUniform is not implemented");return 0};a.WebGL.getAttachedShaders=function(){alert("getAttachedShaders is not implemented");return 0};a.WebGL.getAttribLocation=function(d,b,e){return c.g[d].getAttribLocation(c.o[b],c.C(e))};a.WebGL.getBufferParameter=function(d,b,e){try{return c.g[d].getBufferParameter(b,e)}catch(f){console.log("getBufferParameter error"),console.error(f)}};a.WebGL.getParameter=function(d,b){try{return c.g[d].getParameter(b)}catch(e){console.log("getParameter error"),
console.error(e)}};a.WebGL.getError=function(d){try{return c.g[d].getError()}catch(b){console.log("getError error"),console.error(b)}};a.WebGL.getFramebufferAttachmentParameter=function(d,b,e,f){try{return c.g[d].getParameter(b,e,f)}catch(h){console.log("getFramebufferAttachmentParameter error"),console.error(h)}};a.WebGL.getProgramInfoLog=function(){alert("getProgramInfoLog not implemented");return 0};a.WebGL.getRenderbufferParameter=function(d,b,e){try{return c.g[d].getRenderbufferParameter(b,e)}catch(f){console.log("getRenderbufferParameter error"),
console.error(f)}};a.WebGL.getShaderParameter=function(){alert("getShaderParameter not implemented");return 0};a.WebGL.getShaderPrecisionFormat=function(){alert("getShaderPrecisionFormat not implemented");return 0};a.WebGL.getShaderInfoLog=function(){alert("getShaderInfoLog not implemented");return 0};a.WebGL.getShaderSource=function(){alert("getShaderInfoLog not implemented");return 0};a.WebGL.getTexParameter=function(){alert("getTexParameter not implemented");return 0};a.WebGL.getUniform=function(){alert("getUniform not implemented");
return 0};a.WebGL.getUniformLocation=function(d,b,e){var f=c.i.findIndex(function(h){return null==h});d=c.g[d].getUniformLocation(c.o[b],c.C(e));-1==f?(f=c.i.length,c.i.push(d)):c.i[f]=d;return f};a.WebGL.getVertexAttrib=function(){alert("getVertexAttrib not implemented");return 0};a.WebGL.getVertexAttribOffset=function(d,b,e){try{return c.g[d].getVertexAttribOffset(b,e)}catch(f){console.log("getVertexAttribOffset error"),console.error(f)}};a.WebGL.hint=function(d,b,e){try{return c.g[d].hint(b,e)}catch(f){console.log("hint error"),
console.error(f)}};a.WebGL.isBuffer=function(d,b){try{return c.g[d].isBuffer(c.D[b])}catch(e){console.log("isBuffer error"),console.error(e)}};a.WebGL.isEnabled=function(d,b){try{return c.g[d].isEnabled(b)}catch(e){console.log("isEnabled error"),console.error(e)}};a.WebGL.isFramebuffer=function(d,b){try{return c.g[d].isFramebuffer(c.ta[b])}catch(e){console.log("isFramebuffer error"),console.error(e)}};a.WebGL.isProgram=function(d,b){try{return c.g[d].isProgram(c.o[b])}catch(e){console.log("isProgram error"),
console.error(e)}};a.WebGL.isRenderbuffer=function(d,b){try{return c.g[d].isRenderbuffer(c.H[b])}catch(e){console.log("isRenderbuffer error"),console.error(e)}};a.WebGL.isShader=function(d,b){try{return c.g[d].isShader(c.A[b])}catch(e){console.log("isShader error"),console.error(e)}};a.WebGL.isTexture=function(d,b){try{return c.g[d].isTexture(c.F[b])}catch(e){console.log("isTexture error"),console.error(e)}};a.WebGL.lineWidth=function(d,b){try{return c.g[d].lineWidth(b)}catch(e){console.log("lineWidth error"),
console.error(e)}};a.WebGL.linkProgram=function(d,b){c.g[d].linkProgram(c.o[b]);c.g[d].getProgramParameter(c.o[b],c.g[d].LINK_STATUS)||console.log(c.g[d].getProgramInfoLog(c.o[b]))};a.WebGL.pixelStorei=function(d,b,e){c.g[d].pixelStorei(b,e)};a.WebGL.polygonOffset=function(d,b,e){try{c.g[d].polygonOffset(b,e)}catch(f){console.log("polygonOffset error"),console.error(f)}};a.WebGL.readPixels=function(){alert("readPixels not implemented")};a.WebGL.renderbufferStorage=function(d,b,e,f,h){try{c.g[d].renderbufferStorage(b,
e,f,h)}catch(m){console.log("renderbufferStorage error"),console.error(m)}};a.WebGL.sampleCoverage=function(d,b,e){try{c.g[d].sampleCoverage(b,e)}catch(f){console.log("sampleCoverage error"),console.error(f)}};a.WebGL.scissor=function(d,b,e,f,h){try{c.g[d].scissor(b,e,f,h)}catch(m){console.log("scissor error"),console.error(m)}};a.WebGL.shaderSource=function(d,b,e){c.g[d].shaderSource(c.A[b],c.C(e))};a.WebGL.stencilFunc=function(d,b,e,f){try{c.g[d].stencilFunc(b,e,f)}catch(h){console.log("stencilFunc error"),
console.error(h)}};a.WebGL.stencilFuncSeparate=function(d,b,e,f,h){try{c.g[d].stencilFuncSeparate(b,e,f,h)}catch(m){console.log("stencilFuncSeparate error"),console.error(m)}};a.WebGL.stencilMask=function(d,b){try{c.g[d].stencilMask(b)}catch(e){console.log("stencilMask error"),console.error(e)}};a.WebGL.stencilMaskSeparate=function(d,b,e){try{c.g[d].stencilMaskSeparate(b,e)}catch(f){console.log("stencilMaskSeparate error"),console.error(f)}};a.WebGL.stencilOp=function(){alert("stencilOp is not implemented")};
a.WebGL.stencilOpSeparate=function(){alert("stencilOpSeparate is not implemented")};a.WebGL.texImage2D=function(d,b,e,f,h,m,n){c.g[d].texImage2D(b,e,f,h,m,c.J[n])};a.WebGL.texParameterf=function(d,b,e,f){try{c.g[d].texParameterf(b,e,f)}catch(h){console.log("texParameterf error"),console.error(h)}};a.WebGL.texParameteri=function(d,b,e,f){c.g[d].texParameteri(b,e,f)};a.WebGL.texSubImage2D=function(d,b,e,f,h,m,n,v,r,t){try{c.g[d].texSubImage2D(b,e,f,h,m,n,v,r,c.m(t))}catch(D){console.log("texSubImage2D error"),
console.error(D)}};a.WebGL.uniform1f=function(d,b,e){try{return c.g[d].uniform1f(c.i[b],e)}catch(f){console.log("uniform1f error"),console.error(f)}};a.WebGL.uniform1fv=function(d,b,e){try{return c.g[d].uniform1fv(c.i[b],c.m(e))}catch(f){console.log("uniform1fv error"),console.error(f)}};a.WebGL.uniform1i=function(d,b,e){return c.g[d].uniform1i(c.i[b],e)};a.WebGL.uniform1iv=function(d,b,e){try{return c.g[d].uniform1iv(c.i[b],c.m(e))}catch(f){console.log("uniform1iv error"),console.error(f)}};a.WebGL.uniform2f=
function(d,b,e,f){try{return c.g[d].uniform2f(c.i[b],e,f)}catch(h){console.log("uniform2f error"),console.error(h)}};a.WebGL.uniform2fv=function(d,b,e){try{return c.g[d].uniform2fv(c.i[b],c.m(e))}catch(f){console.log("uniform2fv error"),console.error(f)}};a.WebGL.uniform2i=function(d,b,e,f){try{return c.g[d].uniform2i(c.i[b],e,f)}catch(h){console.log("uniform2i error"),console.error(h)}};a.WebGL.uniform2iv=function(d,b,e){try{return c.g[d].uniform2iv(c.i[b],c.m(e))}catch(f){console.log("uniform2iv error"),
console.error(f)}};a.WebGL.uniform3f=function(d,b,e,f,h){try{return c.g[d].uniform3f(c.i[b],e,f,h)}catch(m){console.log("uniform3f error"),console.error(m)}};a.WebGL.uniform3fv=function(d,b,e){try{return c.g[d].uniform3fv(c.i[b],new Float32Array(e))}catch(f){console.log("uniform3fv error"),console.error(f)}};a.WebGL.uniform3i=function(d,b,e,f,h){try{return c.g[d].uniform3i(c.i[b],e,f,h)}catch(m){console.log("uniform3i error"),console.error(m)}};a.WebGL.uniform3iv=function(d,b,e){try{return c.g[d].uniform3iv(c.i[b],
c.m(e))}catch(f){console.log("uniform3iv error"),console.error(f)}};a.WebGL.uniform4f=function(d,b,e,f,h,m){try{return c.g[d].uniform4f(c.i[b],e,f,h,m)}catch(n){console.log("uniform4f error"),console.error(n)}};a.WebGL.uniform4fv=function(d,b,e){try{return c.g[d].uniform4fv(c.i[b],c.m(e))}catch(f){console.log("uniform4fv error"),console.error(f)}};a.WebGL.uniform4i=function(d,b,e,f,h,m){try{return c.g[d].uniform4i(c.i[b],e,f,h,m)}catch(n){console.log("uniform4i error"),console.error(n)}};a.WebGL.uniform4iv=
function(d,b,e){try{return c.g[d].uniform4iv(c.i[b],c.m(e))}catch(f){console.log("uniform4iv error"),console.error(f)}};a.WebGL.uniformMatrix2fv=function(d,b,e,f){try{return f>>=2,c.g[d].uniformMatrix3fv(c.i[b],e,(new Float32Array(c.memory.buffer)).subarray(f,f+4))}catch(h){console.log("uniformMatrix2fv error"),console.error(h)}};a.WebGL.uniformMatrix3fv=function(d,b,e,f){try{return f>>=2,c.g[d].uniformMatrix3fv(c.i[b],e,(new Float32Array(c.memory.buffer)).subarray(f,f+9))}catch(h){console.log("uniformMatrix3fv error"),
console.error(h)}};a.WebGL.uniformMatrix4fv=function(d,b,e,f){try{return f>>=2,c.g[d].uniformMatrix3fv(c.i[b],e,(new Float32Array(c.memory.buffer)).subarray(f,f+16))}catch(h){console.log("uniformMatrix4fv error"),console.error(h)}};a.WebGL.useProgram=function(d,b){c.g[d].useProgram(c.o[b])};a.WebGL.validateProgram=function(d,b){try{c.g[d].validateProgram(c.o[b])}catch(e){console.log("validateProgram error"),console.error(e)}};a.WebGL.vertexAttrib1f=function(d,b,e){try{return c.g[d].vertexAttrib1f(b,
e)}catch(f){console.log("vertexAttrib1f error"),console.error(f)}};a.WebGL.vertexAttrib1fv=function(d,b,e){try{return c.g[d].vertexAttrib1fv(b,c.m(e))}catch(f){console.log("vertexAttrib1fv error"),console.error(f)}};a.WebGL.vertexAttrib2f=function(d,b,e,f){try{return c.g[d].vertexAttrib2f(b,e,f)}catch(h){console.log("vertexAttrib2f error"),console.error(h)}};a.WebGL.vertexAttrib2fv=function(d,b,e){try{return c.g[d].vertexAttrib2fv(b,c.m(e))}catch(f){console.log("vertexAttrib2fv error"),console.error(f)}};
a.WebGL.vertexAttrib3f=function(d,b,e,f,h){try{return c.g[d].vertexAttrib3f(b,e,f,h)}catch(m){console.log("vertexAttrib3f error"),console.error(m)}};a.WebGL.vertexAttrib3fv=function(d,b,e){try{return c.g[d].vertexAttrib3fv(b,c.m(e))}catch(f){console.log("vertexAttrib3fv error"),console.error(f)}};a.WebGL.vertexAttrib4f=function(d,b,e,f,h,m){try{return c.g[d].vertexAttrib4f(b,e,f,h,m)}catch(n){console.log("vertexAttrib4f error"),console.error(n)}};a.WebGL.vertexAttrib4fv=function(d,b,e){try{return c.g[d].vertexAttrib4fv(b,
c.m(e))}catch(f){console.log("vertexAttrib4fv error"),console.error(f)}};a.WebGL.vertexAttribPointer=function(d,b,e,f,h,m,n){c.g[d].vertexAttribPointer(b,e,f,h,m,n)};a.WebGL.viewport=function(d,b,e,f,h,m){try{c.g[d].viewport(b,e,f,h,m)}catch(n){console.log("viewport error"),console.error(n)}};a.WebGL.copyBufferSubData=function(){alert("copyBufferSubData not implemented (expiramental)")};a.WebGL.getBufferSubData=function(){alert("getBufferSubData not implemented (expiramental)")};a.WebGL.blitFramebuffer=
function(){alert("blitFramebuffer not implemented (expiramental)")};a.WebGL.framebufferTextureLayer=function(){alert("framebufferTextureLayer not implemented (expiramental)")};a.WebGL.invalidateFramebuffer=function(){alert("invalidateFramebuffer not implemented (expiramental)")};a.WebGL.invalidateSubFramebuffer=function(){alert("invalidateSubFramebuffer not implemented (expiramental)")};a.WebGL.readBuffer=function(){alert("readBuffer not implemented (expiramental)")};a.WebGL.getInternalformatParameter=
function(){alert("getInternalformatParameter not implemented (expiramental)")};a.WebGL.renderbufferStorageMultisample=function(){alert("renderbufferStorageMultisample not implemented (expiramental)")};a.WebGL.texStorage2D=function(){alert("texStorage2D not implemented (expiramental)")};a.WebGL.texStorage3D=function(){alert("texStorage3D not implemented (expiramental)")};a.WebGL.texSubImage3D=function(){alert("texSubImage3D not implemented (expiramental)")};a.WebGL.copyTexSubImage3D=function(){alert("copyTexSubImage3D not implemented (expiramental)")};
a.WebGL.compressedTexImage3D=function(){alert("compressedTexImage3D not implemented (expiramental)")};a.WebGL.compressedTexSubImage3D=function(){alert("compressedTexSubImage3D not implemented (expiramental)")};a.WebGL.getFragDataLocation=function(){alert("getFragDataLocation not implemented (expiramental)")};a.WebGL.uniform1ui=function(){alert("uniform1ui not implemented (expiramental)")};a.WebGL.uniform2ui=function(){alert("uniform2ui not implemented (expiramental)")};a.WebGL.uniform3ui=function(){alert("uniform3ui not implemented (expiramental)")};
a.WebGL.uniform4ui=function(){alert("uniform4ui not implemented (expiramental)")};a.WebGL.uniform1uiv=function(){alert("uniform1uiv not implemented (expiramental)")};a.WebGL.uniform2uiv=function(){alert("uniform2uiv not implemented (expiramental)")};a.WebGL.uniform3uiv=function(){alert("uniform3uiv not implemented (expiramental)")};a.WebGL.uniform4uiv=function(){alert("uniform4uiv not implemented (expiramental)")};a.WebGL.uniformMatrix3x2fv=function(){alert("uniformMatrix3x2fv not implemented (expiramental)")};
a.WebGL.uniformMatrix4x2fv=function(){alert("uniformMatrix4x2fv not implemented (expiramental)")};a.WebGL.uniformMatrix2x3fv=function(){alert("uniformMatrix2x3fv not implemented (expiramental)")};a.WebGL.uniformMatrix4x3fv=function(){alert("uniformMatrix4x3fv not implemented (expiramental)")};a.WebGL.uniformMatrix2x4fv=function(){console.trace("uniformMatrix2x4fv");alert("uniformMatrix2x4fv not implemented (expiramental)")};a.WebGL.uniformMatrix3x4fv=function(){console.trace("uniformMatrix3x4fv");
alert("uniformMatrix3x4fv not implemented (expiramental)")};a.WebGL.vertexAttribI4i=function(){console.trace("vertexAttribI4i");alert("vertexAttribI4i not implemented (expiramental)")};a.WebGL.vertexAttribI4iv=function(){console.trace("vertexAttribI4iv");alert("vertexAttribI4iv not implemented (expiramental)")};a.WebGL.vertexAttribI4ui=function(){console.trace("vertexAttribI4ui");alert("vertexAttribI4ui not implemented (expiramental)")};a.WebGL.vertexAttribI4uiv=function(){console.trace("vertexAttribI4uiv");
alert("vertexAttribI4uiv not implemented (expiramental)")};a.WebGL.vertexAttribIPointer=function(){console.trace("vertexAttribIPointer");alert("vertexAttribIPointer not implemented (expiramental)")};a.WebGL.vertexAttribDivisor=function(d,b,e){return c.g[d].vertexAttribDivisor(d,b,e)};a.WebGL.drawArraysInstanced=function(d,b,e,f,h){return c.g[d].drawArraysInstanced(b,e,f,h)};a.WebGL.drawElementsInstanced=function(d,b,e,f,h,m){try{return c.g[d].drawArraysInstanced(b,e,f,h,m)}catch(n){console.log("drawElementsInstanced error"),
console.error(n)}};a.WebGL.drawRangeElements=function(){alert("drawRangeElements not implemented (expiramental)")};a.WebGL.drawBuffers=function(){alert("drawBuffers not implemented (expiramental)")};a.WebGL.clearBufferfv=function(){alert("clearBufferfv not implemented (expiramental)")};a.WebGL.clearBufferiv=function(){alert("clearBufferiv not implemented (expiramental)")};a.WebGL.clearBufferuiv=function(){alert("clearBufferuiv not implemented (expiramental)")};a.WebGL.clearBufferfi=function(){alert("clearBufferfi not implemented (expiramental)")};
a.WebGL.createQuery=function(){alert("createQuery not implemented (expiramental)")};a.WebGL.deleteQuery=function(){alert("deleteQuery not implemented (expiramental)")};a.WebGL.isQuery=function(){alert("isQuery not implemented (expiramental)")};a.WebGL.beginQuery=function(){alert("beginQuery not implemented (expiramental)")};a.WebGL.endQuery=function(){alert("endQuery not implemented (expiramental)")};a.WebGL.getQuery=function(){alert("getQuery not implemented (expiramental)")};a.WebGL.getQueryParameter=
function(){alert("getQueryParameter not implemented (expiramental)")};a.WebGL.createSampler=function(){alert("createSampler not implemented (expiramental)")};a.WebGL.deleteSampler=function(){alert("deleteSampler not implemented (expiramental)")};a.WebGL.isSampler=function(){alert("isSampler not implemented (expiramental)")};a.WebGL.bindSampler=function(){alert("bindSampler not implemented (expiramental)")};a.WebGL.samplerParameteri=function(){alert("samplerParameteri not implemented (expiramental)")};
a.WebGL.samplerParameterf=function(){alert("samplerParameterf not implemented (expiramental)")};a.WebGL.getSamplerParameter=function(){alert("getSamplerParameter not implemented (expiramental)")};a.WebGL.fenceSync=function(){alert("fenceSync not implemented (expiramental)")};a.WebGL.isSync=function(){alert("isSync not implemented (expiramental)")};a.WebGL.deleteSync=function(){alert("deleteSync not implemented (expiramental)")};a.WebGL.clientWaitSync=function(){alert("clientWaitSync not implemented (expiramental)")};
a.WebGL.waitSync=function(){alert("waitSync not implemented (expiramental)")};a.WebGL.getSyncParameter=function(){alert("getSyncParameter not implemented (expiramental)")};a.WebGL.createTransformFeedback=function(){alert("createTransformFeedback not implemented (expiramental)")};a.WebGL.deleteTransformFeedback=function(){alert("deleteTransformFeedback not implemented (expiramental)")};a.WebGL.isTransformFeedback=function(){alert("isTransformFeedback not implemented (expiramental)")};a.WebGL.bindTransformFeedback=
function(){alert("bindTransformFeedback not implemented (expiramental)")};a.WebGL.beginTransformFeedback=function(){alert("beginTransformFeedback not implemented (expiramental)")};a.WebGL.endTransformFeedback=function(){alert("endTransformFeedback not implemented (expiramental)")};a.WebGL.transformFeedbackVaryings=function(){alert("transformFeedbackVaryings not implemented (expiramental)")};a.WebGL.getTransformFeedbackVarying=function(){alert("getTransformFeedbackVarying not implemented (expiramental)")};
a.WebGL.pauseTransformFeedback=function(){alert("pauseTransformFeedback not implemented (expiramental)")};a.WebGL.resumeTransformFeedback=function(){alert("resumeTransformFeedback not implemented (expiramental)")};a.WebGL.bindBufferBase=function(){alert("bindBufferBase not implemented (expiramental)")};a.WebGL.bindBufferRange=function(){alert("bindBufferRange not implemented (expiramental)")};a.WebGL.getIndexedParameter=function(){alert("getIndexedParameter not implemented (expiramental)")};a.WebGL.getUniformIndices=
function(){alert("getUniformIndices not implemented (expiramental)")};a.WebGL.getActiveUniforms=function(){alert("getActiveUniforms not implemented (expiramental)")};a.WebGL.getUniformBlockIndex=function(){alert("getUniformBlockIndex not implemented (expiramental)")};a.WebGL.getActiveUniformBlockParameter=function(){alert("getActiveUniformBlockParameter not implemented (expiramental)")};a.WebGL.getActiveUniformBlockName=function(){alert("getActiveUniformBlockName not implemented (expiramental)")};
a.WebGL.uniformBlockBinding=function(){alert("uniformBlockBinding not implemented (expiramental)")};a.WebGL.createVertexArray=function(d){var b=c.L.findIndex(function(e){return null==e});d=c.g[d].createVertexArray();-1==b?(b=c.L.length,c.L.push(d)):c.L[b]=d;return b};a.WebGL.deleteVertexArray=function(){alert("deleteVertexArray not implemented (expiramental)")};a.WebGL.isVertexArray=function(){alert("isVertexArray not implemented (expiramental)")};a.WebGL.bindVertexArray=function(d,b){c.g[d].bindVertexArray(c.L[b])}}
;var qa="undefined"!==typeof BigUint64Array,C=Symbol(),ra=new TextDecoder("utf-16le");function sa(a,g){var k=(new Uint32Array(a))[g+-4>>>2]>>>1;a=new Uint16Array(a,g,k);return 32>=k?String.fromCharCode.apply(String,a):ra.decode(a)}
function ta(a){function g(d,b){return d?sa(d.buffer,b):"<yet unknown>"}var k={},c=a.ra=a.ra||{};c.abort=c.abort||function(d,b,e,f){var h=k.memory||c.memory;throw Error("abort: "+g(h,d)+" at "+g(h,b)+":"+e+":"+f);};c.trace=c.trace||function(d,b,e){for(var f=[],h=2;h<arguments.length;++h)f[h-2]=arguments[h];console.log("trace: "+g(k.memory||c.memory,d)+(b?" ":"")+f.slice(0,b).join(", "))};c.wa=c.wa||Date.now;a.Math=a.Math||Math;a.Date=a.Date||Date;return k}
function E(){throw Error("Operation requires compiling with --exportRuntime");}
function ua(a,g){function k(l){var q=l;var p=new Uint32Array(h.buffer),u=p[D>>>2];if((q>>>=0)>=u)throw Error("invalid id: "+q);q=p[(D+4>>>2)+2*q];if(!(q&7))throw Error("not an array: "+l+", flags="+q);return q}function c(l,q,p){var u=h.buffer;if(p)switch(l){case 2:return new Float32Array(u);case 3:return new Float64Array(u)}else switch(l){case 0:return new (q?Int8Array:Uint8Array)(u);case 1:return new (q?Int16Array:Uint16Array)(u);case 2:return new (q?Int32Array:Uint32Array)(u);case 3:return new (q?
BigInt64Array:BigUint64Array)(u)}throw Error("unsupported align: "+l);}function d(l){var q=new Uint32Array(h.buffer),p=k(q[l+-8>>>2]),u=31-Math.clz32(p>>>6&31),x=p&4?l:q[l+4>>>2];l=p&2?q[l+12>>>2]:q[x+-4>>>2]>>>u;return c(u,p&2048,p&4096).subarray(x>>>=u,x+l)}function b(l,q,p){return new l(e(l,q,p))}function e(l,q,p){var u=h.buffer,x=new Uint32Array(u);p=x[p+4>>>2];return new l(u,p,x[p+-4>>>2]>>>q)}function f(l,q,p){a["__get"+q]=b.bind(null,l,p);a["__get"+q+"View"]=e.bind(null,l,p)}g=g.exports;var h=
g.memory,m=g.table,n=g.qa||E,v=g.U||E,r=g.V||E,t=g.oa||E,D=g.kb||-1;a.qa=n;a.U=v;a.V=r;a.oa=t;a.jb=function(l){if(null==l)return 0;for(var q=l.length,p=n(q<<1,1),u=new Uint16Array(h.buffer),x=0,H=p>>>1;x<q;++x)u[H+x]=l.charCodeAt(x);return p};a.M=function(l){if(!l)return null;var q=h.buffer;if(1!==(new Uint32Array(q))[l+-8>>>2])throw Error("not a string: "+l);return sa(q,l)};a.Y=function(l,q){var p=k(l),u=31-Math.clz32(p>>>6&31),x=q.length,H=n(x<<u,p&4?l:0);if(p&4)l=H;else{v(H);l=n(p&2?16:12,l);r(H);
var K=new Uint32Array(h.buffer);K[l+0>>>2]=H;K[l+4>>>2]=H;K[l+8>>>2]=x<<u;p&2&&(K[l+12>>>2]=x)}K=c(u,p&2048,p&4096);if(p&16384)for(p=0;p<x;++p)K[(H>>>u)+p]=q[p];else K.set(q,H>>>u);return l};a.hb=d;a.fb=function(l){l=d(l);for(var q=l.length,p=Array(q),u=0;u<q;u++)p[u]=l[u];return p};a.gb=function(l){var q=h.buffer,p=(new Uint32Array(q))[l+-4>>>2];return q.slice(l,l+p)};[Int8Array,Uint8Array,Uint8ClampedArray,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array].forEach(function(l){f(l,
l.name,31-Math.clz32(l.BYTES_PER_ELEMENT))});qa&&[BigUint64Array,BigInt64Array].forEach(function(l){f(l,l.name.slice(3),3)});a.ib=function(l,q){var p=new Uint32Array(h.buffer);l=p[l+-8>>>2];if(l<=p[D>>>2]){do{if(l==q)return!0;p=l;l=new Uint32Array(h.buffer);var u=l[D>>>2];if((p>>>=0)>=u)throw Error("invalid id: "+p);l=l[(D+4>>>2)+2*p+1]}while(l)}return!1};a.memory=a.memory||h;a.table=a.table||m;return va(g,a)}function wa(a){return"undefined"!==typeof Response&&a instanceof Response}
function xa(a,g){g=void 0===g?{}:g;var k,c,d,b,e,f;return na(function(h){switch(h.h){case 1:return k=wa,A(h,a,2);case 2:if(k(a=h.l))return h.return(ya(a,g));if(a instanceof WebAssembly.Module){c=a;h.h=3;break}return A(h,WebAssembly.compile(a),4);case 4:c=h.l;case 3:return d=c,b=ta(g),A(h,WebAssembly.instantiate(d,g),5);case 5:return e=h.l,f=ua(b,e),h.return({module:d,instance:e,exports:f})}})}
function ya(a,g){g=void 0===g?{}:g;var k,c,d,b,e;return na(function(f){switch(f.h){case 1:if(WebAssembly.instantiateStreaming){f.h=2;break}k=xa;c=wa;return A(f,a,3);case 3:return f.return(k(c(a=f.l)?a.arrayBuffer():a,g));case 2:return d=ta(g),A(f,WebAssembly.instantiateStreaming(a,g),4);case 4:return b=f.l,e=ua(d,b.instance),f.return(Object.assign({},b,{exports:e}))}})}
function va(a,g){g=void 0===g?{}:g;var k=a.__argumentsLength?function(n){a.__argumentsLength.value=n}:a.__setArgumentsLength||a.__setargc||function(){},c={},d;for(d in a){if(Object.prototype.hasOwnProperty.call(a,d)){c.s=a[d];for(var b=d.split("."),e=g;1<b.length;){var f=b.shift();Object.prototype.hasOwnProperty.call(e,f)||(e[f]={});e=e[f]}b=b[0];f=b.indexOf("#");if(0<=f){var h=b.substring(0,f);c.G=e[h];"undefined"!==typeof c.G&&c.G.prototype||(c.B=function(n){return function(v){for(var r=[],t=0;t<
arguments.length;++t)r[t]=arguments[t];return n.B.za(n.B.prototype.constructor.apply(n.B.prototype,[0].concat(w(r))))}}(c),c.B.prototype={valueOf:function(){return this[C]}},c.B.za=function(n){return function(v){var r={};return Object.create(n.B.prototype,(r[C]={value:v,writable:!1},r))}}(c),c.G&&Object.getOwnPropertyNames(c.G).forEach(function(n){return function(v){return Object.defineProperty(n.B,v,Object.getOwnPropertyDescriptor(n.G,v))}}(c)),e[h]=c.B);b=b.substring(f+1);e=e[h].prototype;if(/^(get|set):/.test(b))Object.prototype.hasOwnProperty.call(e,
b=b.substring(4))||(c.O=a[d.replace("set:","get:")],c.P=a[d.replace("get:","set:")],Object.defineProperty(e,b,{get:function(n){return function(){return n.O(this[C])}}(c),set:function(n){return function(v){n.P(this[C],v)}}(c),enumerable:!0}));else if("constructor"===b)(e[b]=function(n){return function(v){for(var r=[],t=0;t<arguments.length;++t)r[t]=arguments[t];k(r.length);return n.s.apply(null,w(r))}}(c)).$=c.s;else{var m=this;(e[b]=function(n){return function(v){for(var r=[],t=0;t<arguments.length;++t)r[t]=
arguments[t];k(r.length);return n.s.apply(null,[m[C]].concat(w(r)))}}(c)).$=c.s}}else/^(get|set):/.test(b)?Object.prototype.hasOwnProperty.call(e,b=b.substring(4))||Object.defineProperty(e,b,{get:a[d.replace("set:","get:")],set:a[d.replace("get:","set:")],enumerable:!0}):"function"===typeof c.s&&c.s!==k?(e[b]=function(n){return function(v){for(var r=[],t=0;t<arguments.length;++t)r[t]=arguments[t];k(r.length);return n.s.apply(null,w(r))}}(c)).$=c.s:e[b]=c.s}c={B:c.B,G:c.G,O:c.O,P:c.P,s:c.s}}return g}
;var za=Math.random().toString(36).substr(2,9),Aa,F,G=document.getElementById("cnvs"),Ba=new Audio("audio/replica.mp3"),Ca=new Audio("audio/deadly_slot_game.mp3"),Da=new Audio("audio/aesir_chaos.mp3"),Ea=new Audio("audio/laserSmall_000.ogg"),Fa=new Audio("audio/explosion-hq.mp3"),I="chill",J={chill:Ba,fight1:Ca,fight2:Da},Ga={laser:Ea,explosion:Fa},L=null,M=null,N=null,O=null,P=0,Q=null,R=null,S=100;function Ha(){null!=O&&(O.close(),O=null)}
function Ia(){function a(){Q=setTimeout(function(){F.Ta();a()},S+(20*Math.random()-10));S*=2;1E3<S&&(S=1E3)}F.ka(performance.now());S=100;a();R=setInterval(function(){F.Pa()},100)}function Ja(){null!=Q&&(clearTimeout(Q),Q=null);null!=R&&(clearInterval(R),R=null);null!=M&&(M.close(),M=null);null!=N&&(N.close(),N=null);null!=L&&(L.close(),L=null);P=0}
function Ka(a){null!=L?console.error("StartRTCPeerConnection: webrtc_conn not null"):(L=new RTCPeerConnection(null),M=L.createDataChannel("unreliable",{ordered:!1,maxPacketLifeTime:100}),M.onopen=function(){P++;2<=P&&F.ka(performance.now())},M.onerror=function(g){console.log("onerror:",M.readyState,g)},M.onclose=function(){F.ja();Ha();Ja()},M.onmessage=function(g){var k=performance.now();g=F.U(F.Y(F.ma,new Uint8Array(g.data)));F.Oa(k,g);F.V(g)},M.onbufferedamountlow=function(){},N=L.createDataChannel("reliable",
{ordered:!0,maxRetransmits:1E3}),N.onopen=function(){P++;2<=P&&Ia()},N.onerror=function(g){console.log("onerror:",N.readyState,g)},N.onclose=function(){F.ja();Ha();Ja()},N.onmessage=function(g){g=F.U(F.Y(F.ma,new Uint8Array(g.data)));F.Na(g);F.V(g)},N.onbufferedamountlow=function(){},L.createOffer().then(function(g){return L.setLocalDescription(g)}).then(function(){a(L.localDescription)}).catch(function(g){console.error("createOffer failed: "+g);Ha();Ja()}))}
function La(){O=new WebSocket("wss://"+location.hostname+":8443/bb/"+za);O.onopen=function(){console.log("WebSocket client connected");L||Ka(function(a){null!=O?O.send(JSON.stringify({type:"offer",tb:a})):Ja()})};O.onclose=function(){console.error("WebSocket client disconnected");O=null;setTimeout(function(){location.reload()},3E3);setTimeout(function(){La()},1E3)};O.onerror=function(a){console.error("WebSocket error",a)};O.onmessage=function(a){try{var g=JSON.parse(a.data);"answer"==g.type&&null!=
L?L.setRemoteDescription(new RTCSessionDescription({type:"answer",sdp:g.sdp})):"candidate"==g.type&&null!=L&&L.addIceCandidate(new RTCIceCandidate({candidate:g.candidate,sdpMid:g.mid}))}catch(k){console.error("Websocket message parse failed: err=",k)}}}var T=!1,Ma=0,Na=0,U=0,V=0,W=!1;
function Oa(){T||(T=!0,document.body.style.backgroundColor="#444",Ma=parseInt(window.getComputedStyle(G.parentNode).getPropertyValue("margin-left"),10),Na=parseInt(window.getComputedStyle(G.parentNode).getPropertyValue("margin-top"),10),W&&(J[I].play(),J[I].loop=!0))}function Pa(){T&&(T=!1,V=U=-1,document.body.style.backgroundColor="white",W&&J[I].pause())}
function Qa(a){a.touches?(U=a.targetTouches[0].clientX-Ma,V=a.targetTouches[0].clientY-Na):a.offsetX?(U=a.offsetX,V=a.offsetY):a.layerX&&(U=a.layerX,V=a.layerY)}G.addEventListener("touchmove",function(a){a.preventDefault();Qa(a)},{passive:!1});G.addEventListener("MozTouchMove",function(a){a.preventDefault();Qa(a)},{passive:!1});G.addEventListener("mousemove",function(a){Qa(a)},{passive:!0});G.addEventListener("touchstart",function(a){a.preventDefault();Oa()},{passive:!1});
G.addEventListener("MozTouchDown",function(a){a.preventDefault();Oa()},{passive:!1});G.addEventListener("mouseover",function(){Oa()},{passive:!0});G.addEventListener("touchend",function(a){a.preventDefault();Pa()},{passive:!1});G.addEventListener("MozTouchUp",function(a){a.preventDefault();Pa()},{passive:!1});G.addEventListener("mouseout",function(){Pa()},{passive:!0});document.addEventListener("mousedown",function(){W||(W=!0,J[I].play(),J[I].loop=!0)},{passive:!0});var Ra=0,Sa=0,X=0,Y=0,Ta=0;
function Ua(){(window.innerWidth!=Ra||window.innerHeight!=Sa)&&100<=performance.now()-Ta&&(Ra=window.innerWidth,Sa=window.innerHeight,X=.98*Ra-32,Y=.98*Sa-32,X>Y?X=Y:Y=X,G.width=X,G.height=X,G.style.width=X+"px",G.style.height=X+"px",Ta=performance.now());F.Qa(performance.now(),U,V,X,Y);requestAnimationFrame(Ua)}var Z={netcode:{}};Z.netcode.consoleLog=function(a){var g=F.M(a);setTimeout(function(){console.log(g)},50)};Z.netcode.getMilliseconds=function(){return performance.now()};Z.client={};
Z.client.sendReliable=function(a){null!=N&&N.send(F.pa(a))};Z.client.sendUnreliable=function(a){null!=M&&M.send(F.pa(a))};Z.client.playMusic=function(a){var g=F.M(a);setTimeout(function(){if(I!=g){var k=I,c=function(){var e=J[k].volume-.1;0>=e?J[k].pause():(J[k].volume=e,setTimeout(c,100))};c()}I=g;if(W){var d=I;J[d].volume=.1;T&&J[d].play();var b=function(){var e=J[d].volume+.1;1>e?(J[d].volume=e,setTimeout(b,100)):J[d].volume=1};b();J[I].loop=!0}},0)};
Z.client.playSFX=function(a){var g=F.M(a);setTimeout(function(){W&&(Ga[g].pause(),Ga[g].play())},0)};Z.client.serverLoginGood=function(){console.log("LoginGood")};Z.client.serverLoginBad=function(a){a=F.M(a);console.error("LoginBad:",a)};Z.env={};
(function(a){var g=new WebAssembly.Memory({initial:1E4}),k=Object.assign({},Z);k.env.memory=g;pa(k);(function(){var c;return na(function(d){if(1==d.h)return A(d,fetch(a),2);c=d.l;ya(c,k).then(function(b){Aa=b;F=Aa.exports;console.log("ASWebGLReady");null==b?console.error("ASWebGLReady requires the WebAssembly Instance as 1st parameter"):null==b?console.error("ASWebGLReady requires import object as 2nd parameter"):(k.WebGL.na=!0,console.log("========================="),console.log(b.instance.exports),
console.log(b.instance.exports.__rtti_base),k.WebGL.S=b.instance.exports.__rtti_base);F.Ca();La();requestAnimationFrame(Ua)});d.h=0})})()})("client.wasm");
