function aa(a){var g=0;return function(){return g<a.length?{done:!1,value:a[g++]}:{done:!0}}}function ba(a){var g="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return g?g.call(a):{next:aa(a)}}function w(a){if(!(a instanceof Array)){a=ba(a);for(var g,k=[];!(g=a.next()).done;)k.push(g.value);a=k}return a}var ca="function"==typeof Object.defineProperties?Object.defineProperty:function(a,g,k){if(a==Array.prototype||a==Object.prototype)return a;a[g]=k.value;return a};
function da(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var g=0;g<a.length;++g){var k=a[g];if(k&&k.Math==Math)return k}throw Error("Cannot find global object");}var y=da(this);function z(a,g){if(g)a:{var k=y;a=a.split(".");for(var c=0;c<a.length-1;c++){var d=a[c];if(!(d in k))break a;k=k[d]}a=a[a.length-1];c=k[a];g=g(c);g!=c&&null!=g&&ca(k,a,{configurable:!0,writable:!0,value:g})}}
function ea(){this.A=!1;this.l=null;this.m=void 0;this.i=1;this.M=0;this.v=null}function fa(a){if(a.A)throw new TypeError("Generator is already running");a.A=!0}ea.prototype.J=function(a){this.m=a};function ha(a,g){a.v={ta:g,wa:!0};a.i=a.M}ea.prototype.return=function(a){this.v={return:a};this.i=this.M};function A(a,g,k){a.i=k;return{value:g}}function ia(a){this.i=new ea;this.l=a}
function ja(a,g){fa(a.i);var k=a.i.l;if(k)return ka(a,"return"in k?k["return"]:function(c){return{value:c,done:!0}},g,a.i.return);a.i.return(g);return B(a)}function ka(a,g,k,c){try{var d=g.call(a.i.l,k);if(!(d instanceof Object))throw new TypeError("Iterator result "+d+" is not an object");if(!d.done)return a.i.A=!1,d;var b=d.value}catch(e){return a.i.l=null,ha(a.i,e),B(a)}a.i.l=null;c.call(a.i,b);return B(a)}
function B(a){for(;a.i.i;)try{var g=a.l(a.i);if(g)return a.i.A=!1,{value:g.value,done:!1}}catch(k){a.i.m=void 0,ha(a.i,k)}a.i.A=!1;if(a.i.v){g=a.i.v;a.i.v=null;if(g.wa)throw g.ta;return{value:g.return,done:!0}}return{value:void 0,done:!0}}
function la(a){this.next=function(g){fa(a.i);a.i.l?g=ka(a,a.i.l.next,g,a.i.J):(a.i.J(g),g=B(a));return g};this.throw=function(g){fa(a.i);a.i.l?g=ka(a,a.i.l["throw"],g,a.i.J):(ha(a.i,g),g=B(a));return g};this.return=function(g){return ja(a,g)};this[Symbol.iterator]=function(){return this}}function ma(a){function g(c){return a.next(c)}function k(c){return a.throw(c)}return new Promise(function(c,d){function b(e){e.done?c(e.value):Promise.resolve(e.value).then(g,k).then(b,d)}b(a.next())})}
function na(a){return ma(new la(new ia(a)))}z("Symbol",function(a){function g(b){if(this instanceof g)throw new TypeError("Symbol is not a constructor");return new k(c+(b||"")+"_"+d++,b)}function k(b,e){this.i=b;ca(this,"description",{configurable:!0,writable:!0,value:e})}if(a)return a;k.prototype.toString=function(){return this.i};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",d=0;return g});
z("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var g="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),k=0;k<g.length;k++){var c=y[g[k]];"function"===typeof c&&"function"!=typeof c.prototype[a]&&ca(c.prototype,a,{configurable:!0,writable:!0,value:function(){return oa(aa(this))}})}return a});function oa(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
z("Promise",function(a){function g(e){this.l=0;this.m=void 0;this.i=[];this.M=!1;var f=this.v();try{e(f.resolve,f.reject)}catch(h){f.reject(h)}}function k(){this.i=null}function c(e){return e instanceof g?e:new g(function(f){f(e)})}if(a)return a;k.prototype.l=function(e){if(null==this.i){this.i=[];var f=this;this.m(function(){f.A()})}this.i.push(e)};var d=y.setTimeout;k.prototype.m=function(e){d(e,0)};k.prototype.A=function(){for(;this.i&&this.i.length;){var e=this.i;this.i=[];for(var f=0;f<e.length;++f){var h=
e[f];e[f]=null;try{h()}catch(m){this.v(m)}}}this.i=null};k.prototype.v=function(e){this.m(function(){throw e;})};g.prototype.v=function(){function e(m){return function(n){h||(h=!0,m.call(f,n))}}var f=this,h=!1;return{resolve:e(this.ga),reject:e(this.A)}};g.prototype.ga=function(e){if(e===this)this.A(new TypeError("A Promise cannot resolve to itself"));else if(e instanceof g)this.ia(e);else{a:switch(typeof e){case "object":var f=null!=e;break a;case "function":f=!0;break a;default:f=!1}f?this.da(e):
this.J(e)}};g.prototype.da=function(e){var f=void 0;try{f=e.then}catch(h){this.A(h);return}"function"==typeof f?this.ja(f,e):this.J(e)};g.prototype.A=function(e){this.ca(2,e)};g.prototype.J=function(e){this.ca(1,e)};g.prototype.ca=function(e,f){if(0!=this.l)throw Error("Cannot settle("+e+", "+f+"): Promise already settled in state"+this.l);this.l=e;this.m=f;2===this.l&&this.ha();this.ya()};g.prototype.ha=function(){var e=this;d(function(){if(e.za()){var f=y.console;"undefined"!==typeof f&&f.error(e.m)}},
1)};g.prototype.za=function(){if(this.M)return!1;var e=y.CustomEvent,f=y.Event,h=y.dispatchEvent;if("undefined"===typeof h)return!0;"function"===typeof e?e=new e("unhandledrejection",{cancelable:!0}):"function"===typeof f?e=new f("unhandledrejection",{cancelable:!0}):(e=y.document.createEvent("CustomEvent"),e.initCustomEvent("unhandledrejection",!1,!0,e));e.promise=this;e.reason=this.m;return h(e)};g.prototype.ya=function(){if(null!=this.i){for(var e=0;e<this.i.length;++e)b.l(this.i[e]);this.i=null}};
var b=new k;g.prototype.ia=function(e){var f=this.v();e.P(f.resolve,f.reject)};g.prototype.ja=function(e,f){var h=this.v();try{e.call(f,h.resolve,h.reject)}catch(m){h.reject(m)}};g.prototype.then=function(e,f){function h(r,t){return"function"==typeof r?function(D){try{m(r(D))}catch(l){n(l)}}:t}var m,n,v=new g(function(r,t){m=r;n=t});this.P(h(e,m),h(f,n));return v};g.prototype.catch=function(e){return this.then(void 0,e)};g.prototype.P=function(e,f){function h(){switch(m.l){case 1:e(m.m);break;case 2:f(m.m);
break;default:throw Error("Unexpected state: "+m.l);}}var m=this;null==this.i?b.l(h):this.i.push(h);this.M=!0};g.resolve=c;g.reject=function(e){return new g(function(f,h){h(e)})};g.race=function(e){return new g(function(f,h){for(var m=ba(e),n=m.next();!n.done;n=m.next())c(n.value).P(f,h)})};g.all=function(e){var f=ba(e),h=f.next();return h.done?c([]):new g(function(m,n){function v(D){return function(l){r[D]=l;t--;0==t&&m(r)}}var r=[],t=0;do r.push(void 0),t++,c(h.value).P(v(r.length-1),n),h=f.next();
while(!h.done)})};return g});z("Math.clz32",function(a){return a?a:function(g){g=Number(g)>>>0;if(0===g)return 32;var k=0;0===(g&4294901760)&&(g<<=16,k+=16);0===(g&4278190080)&&(g<<=8,k+=8);0===(g&4026531840)&&(g<<=4,k+=4);0===(g&3221225472)&&(g<<=2,k+=2);0===(g&2147483648)&&k++;return k}});z("Array.prototype.findIndex",function(a){return a?a:function(g,k){a:{var c=this;c instanceof String&&(c=String(c));for(var d=c.length,b=0;b<d;b++)if(g.call(k,c[b],b,c)){g=b;break a}g=-1}return g}});
function pa(a){function g(d,b,e,f){c.h[d].bufferData(b,c.o(e),f)}var k=arguments;null==a.K.memory&&alert("You need to set memory in your importObject");null==a.g&&(a.g={});var c=a.g;a.K.abort=function(d){for(var b=[],e=0;e<arguments.length;++e)b[e]=arguments[e];console.log("abort");console.log(c.D(b[0]))};a.g.pa=!1;a.g.memory=a.K.memory;a.g.h=[];a.g.G=[];a.g.L=[];a.g.s=[];a.g.B=[];a.g.F=[];a.g.ua=[];a.g.I=[];a.g.j=[];a.g.N=[];a.g.na=-4;a.g.ka=-8;a.g.Ca=1024;a.g.Ta=1;a.g.U=0;a.g.Z=6;a.ea=4;a.fa=12;
a.g.NONE=0;a.g.Y=1;a.g.T=2;a.g.V=4;a.g.Sa=8;a.g.Na=16;a.g.Ba=32;a.g.Va=64;a.g.Wa=128;a.g.Xa=256;a.g.Ya=512;a.g.Za=1024;a.g.cb=2048;a.g.$a=4096;a.g.bb=8192;a.g.ab=16384;a.g.Ea=32768;a.g.Fa=65536;a.g.Ga=131072;a.g.Ha=262144;a.g.Ia=524288;a.g.Ma=1048576;a.g.Ja=2097152;a.g.La=4194304;a.g.Ka=8388608;a.g.ob=function(d){console.log("createImage("+d+")");var b=new Image;b.ready=!1;b.onload=function(){b.ready=!0};b.src=c.D(d);console.log("image.src="+b.src);d=c.L.length;c.L.push(b);return d};a.g.ub=function(d){console.log("logi32="+
d)};a.g.tb=function(d){console.log("logf32="+d)};a.g.sb=function(d){return c.L.length<=d?!1:c.L[d].ready};a.g.va=function(d,b,e){var f=c.memory.buffer;if(e)switch(d){case 2:return new Float32Array(f);case 3:return new Float64Array(f)}else switch(d){case 0:return new (b?Int8Array:Uint8Array)(f);case 1:return new (b?Int16Array:Uint16Array)(f);case 2:return new (b?Int32Array:Uint32Array)(f);case 3:return new (b?BigInt64Array:BigUint64Array)(f)}throw Error("unsupported align: "+d);};a.g.pb=function(d){var b=
c.qb(d);if(!(b&(c.Y|c.T|c.V)))throw Error("not an array: "+d+", flags="+b);return b};a.g.rb=function(d){return 31-Math.clz32(d>>>c.Z&31)};a.g.o=function(d){var b=new Uint32Array(c.memory.buffer),e=b[d+c.ka>>>2];if(e>=b[c.U>>>2])throw Error("invalid id: "+e);var f=b[(c.U+4>>>2)+2*e];if(!(f&(c.Y|c.T|c.V)))throw Error("not an array: "+e+", flags="+f);e=31-Math.clz32(f>>>c.Z&31);var h=f&c.V?d:b[d+c.ea>>>2];d=f&c.T?b[d+c.fa>>>2]:b[h+c.na>>>2]>>>e;return c.va(e,f&c.fb,f&c.eb).subarray(h>>>=e,h+d)};a.g.D=
function(d){var b=c.memory.buffer,e=new Uint32Array(b),f=d/4-2,h=e[f];if(1!==h)throw Error("not a string index="+d+" id="+h);e=e[f+1];return(new TextDecoder("utf-16")).decode(b.slice(d,d+e))};a.g.nb=function(d,b){d=document.getElementById(c.D(d)).getContext(c.D(b),{alpha:!1});b=c.h.findIndex(function(e){return null==e});-1==b?(b=c.h.length,c.h.push(d)):c.h[b]=d;return b};a.g.getSupportedExtensions=function(){alert("getSupportedExtensions is not currently supported")};a.g.getExtension=function(d,b){c.h[d].getExtension(c.D(b))};
a.g.activeTexture=function(d,b){c.h[d].activeTexture(b)};a.g.attachShader=function(d,b,e){c.h[d].attachShader(c.s[b],c.B[e])};a.g.bindAttribLocation=function(d,b,e,f){c.h[d].bindAttribLocation(c.s[b],e,c.D(f))};a.g.bindBuffer=function(d,b,e){c.h[d].bindBuffer(b,c.F[e])};a.g.bindFramebuffer=function(d,b,e){c.h[d].bindFramebuffer(b,c.aa[e])};a.g.bindRenderbuffer=function(d,b,e){c.h[d].bindRenderbuffer(b,c.Ab[e])};a.g.bindTexture=function(d,b,e){c.h[d].bindTexture(b,c.G[e])};a.g.blendColor=function(d,
b,e,f,h){c.h[d].blendColor(b,e,f,h)};a.g.blendEquation=function(d,b){c.h[d].blendEquation(b)};a.g.blendEquationSeparate=function(d,b,e){c.h[d].blendEquationSeparate(b,e)};a.g.blendFunc=function(d,b,e){c.h[d].blendFunc(b,e)};a.g.blendFuncSeparate=function(d,b,e,f,h){c.h[d].blendFuncSeparate(b,e,f,h)};a.g["bufferData<f32>"]=g;a.g["bufferData<f64>"]=g;a.g["bufferData<i32>"]=g;a.g["bufferData<u16>"]=g;a.g["bufferData<u8>"]=g;a.g.bufferSubData=function(d,b,e,f,h,m){c.h[d].bufferSubData(b,e,c.o(f),h,m)};
a.g.checkFramebufferStatus=function(d,b){return c.h[d].checkFramebufferStatus(b)};a.g.clear=function(d,b){c.h[d].clear(b)};a.g.clearColor=function(d,b,e,f,h){c.h[d].clearColor(b,e,f,h)};a.g.clearDepth=function(d,b){c.h[d].clearDepth(b)};a.g.clearStencil=function(d,b){c.h[d].clearStencil(b)};a.g.colorMask=function(d,b,e,f,h){c.h[d].colorMask(b,e,f,h)};a.g.compileShader=function(d,b){c.h[d].compileShader(c.B[b]);d=c.h[d].getShaderInfoLog(c.B[b]);console.log(d)};a.g.compressedTexImage2D=function(d,b,
e,f,h,m,n,v){c.h[d].compileShader(b,e,f,h,m,n,c.o(v))};a.g.compressedTexSubImage2D=function(d,b,e,f,h,m,n,v,r){c.h[d].compressedTexSubImage2D(b,f,h,m,n,v,c.o(r))};a.g.copyTexImage2D=function(d,b,e,f,h,m,n,v,r){c.h[d].copyTexImage2D(b,e,f,h,m,n,v,r)};a.g.copyTexSubImage2D=function(d,b,e,f,h,m,n,v,r){c.h[d].copyTexSubImage2D(b,e,f,h,m,n,v,r)};a.g.createBuffer=function(d){var b=c.F.findIndex(function(e){return null==e});d=c.h[d].createBuffer();-1==b?(b=c.F.length,c.F.push(d)):c.F[b]=d;return b};a.g.createFramebuffer=
function(){alert(k.callee.toString())};a.g.createProgram=function(d){var b=c.s.findIndex(function(e){return null==e});d=c.h[d].createProgram();-1==b?(b=c.s.length,c.s.push(d)):c.s[b]=d;return b};a.g.createRenderbuffer=function(d){try{var b=c.I.findIndex(function(f){return null==f}),e=c.h[d].createRenderbuffer();-1==b?(b=c.I.length,c.I.push(e)):c.I[b]=e;return b}catch(f){console.log("renderBufferArray error"),console.error(f)}};a.g.createShader=function(d,b){var e=c.B.findIndex(function(f){return null==
f});d=c.h[d].createShader(b);-1==e?(e=c.B.length,c.B.push(d)):c.B[e]=d;return e};a.g.createTexture=function(d){var b=c.G.findIndex(function(e){return null==e});d=c.h[d].createTexture();-1==b?(b=c.G.length,c.G.push(d)):c.G[b]=d;return b};a.g.cullFace=function(d,b){try{c.h[d].cullFace(b)}catch(e){console.log("cullFace error"),console.error(e)}};a.g.deleteBuffer=function(d,b){try{c.h[d].deleteBuffer(c.F[b]),c.F[b]=null}catch(e){console.log("deleteBuffer error"),console.error(e)}};a.g.deleteFramebuffer=
function(d,b){try{c.h[d].deleteFramebuffer(c.aa[b]),c.aa[b]=null}catch(e){console.log("deleteFramebuffer error"),console.error(e)}};a.g.deleteRenderbuffer=function(d,b){try{c.h[d].deleteRenderbuffer(c.I[b]),c.I[b]=null}catch(e){console.log("deleteRenderbuffer error"),console.error(e)}};a.g.deleteProgram=function(d,b){try{c.h[d].deleteProgram(c.s[b]),c.zb[b]=null}catch(e){console.log("deleteProgram error"),console.error(e)}};a.g.deleteShader=function(d,b){try{c.h[d].deleteShader(c.B[b]),c.B[b]=null}catch(e){console.log("deleteShader error"),
console.error(e)}};a.g.deleteTexture=function(d,b){try{c.h[d].deleteShader(c.G[b]),c.G[b]=null}catch(e){console.log("deleteTexture error"),console.error(e)}};a.g.depthFunc=function(d,b){try{c.h[d].depthFunc(b)}catch(e){console.log("depthFunc error"),console.error(e)}};a.g.depthMask=function(d,b){try{c.h[d].depthMask(b)}catch(e){console.log("depthMask error"),console.error(e)}};a.g.depthRange=function(d,b,e){try{c.h[d].depthRange(b,e)}catch(f){console.log("depthRange error"),console.error(f)}};a.g.detachShader=
function(d,b,e){try{c.h[d].detachShader(b,e)}catch(f){console.log("detachShader error"),console.error(f)}};a.g.disable=function(d,b){try{c.h[d].disable(b)}catch(e){console.log("disable error"),console.error(e)}};a.g.disableVertexAttribArray=function(d,b){try{c.h[d].disableVertexAttribArray(b)}catch(e){console.log("disableVertexAttribArray error"),console.error(e)}};a.g.drawArrays=function(d,b,e,f){try{c.h[d].drawArrays(b,e,f)}catch(h){console.log("drawArrays error"),console.error(h)}};a.g.drawElements=
function(d,b,e,f,h){try{c.h[d].drawElements(b,e,f,h)}catch(m){console.log("drawElements error"),console.error(m)}};a.g.enable=function(d,b){try{c.h[d].enable(b)}catch(e){console.log("enable error"),console.error(e)}};a.g.enableVertexAttribArray=function(d,b){c.h[d].enableVertexAttribArray(b)};a.g.finish=function(d){try{c.h[d].finish()}catch(b){console.log("finish error"),console.error(b)}};a.g.flush=function(d){try{c.h[d].flush()}catch(b){console.log("flush error"),console.error(b)}};a.g.framebufferRenderbuffer=
function(d,b,e,f,h){try{c.h[d].framebufferRenderbuffer(b,e,f,h)}catch(m){console.log("framebufferRenderbuffer error"),console.error(m)}};a.g.framebufferTexture2D=function(d,b,e,f,h,m){try{c.h[d].framebufferTexture2D(b,e,f,h,m)}catch(n){console.log("framebufferTexture2D error"),console.error(n)}};a.g.frontFace=function(d,b){try{c.h[d].frontFace(b)}catch(e){console.log("frontFace error"),console.error(e)}};a.g.generateMipmap=function(d,b){try{c.h[d].generateMipmap(b)}catch(e){console.log("generateMipmap error"),
console.error(e)}};a.g.getActiveAttrib=function(){alert("getActiveAttrib is not implemented");return 0};a.g.getActiveUniform=function(){alert("getActiveUniform is not implemented");return 0};a.g.getAttachedShaders=function(){alert("getAttachedShaders is not implemented");return 0};a.g.getAttribLocation=function(d,b,e){return c.h[d].getAttribLocation(c.s[b],c.D(e))};a.g.getBufferParameter=function(d,b,e){try{return c.h[d].getBufferParameter(b,e)}catch(f){console.log("getBufferParameter error"),console.error(f)}};
a.g.getParameter=function(d,b){try{return c.h[d].getParameter(b)}catch(e){console.log("getParameter error"),console.error(e)}};a.g.getError=function(d){try{return c.h[d].getError()}catch(b){console.log("getError error"),console.error(b)}};a.g.getFramebufferAttachmentParameter=function(d,b,e,f){try{return c.h[d].getParameter(b,e,f)}catch(h){console.log("getFramebufferAttachmentParameter error"),console.error(h)}};a.g.getProgramInfoLog=function(){alert("getProgramInfoLog not implemented");return 0};
a.g.getRenderbufferParameter=function(d,b,e){try{return c.h[d].getRenderbufferParameter(b,e)}catch(f){console.log("getRenderbufferParameter error"),console.error(f)}};a.g.getShaderParameter=function(){alert("getShaderParameter not implemented");return 0};a.g.getShaderPrecisionFormat=function(){alert("getShaderPrecisionFormat not implemented");return 0};a.g.getShaderInfoLog=function(){alert("getShaderInfoLog not implemented");return 0};a.g.getShaderSource=function(){alert("getShaderInfoLog not implemented");
return 0};a.g.getTexParameter=function(){alert("getTexParameter not implemented");return 0};a.g.getUniform=function(){alert("getUniform not implemented");return 0};a.g.getUniformLocation=function(d,b,e){var f=c.j.findIndex(function(h){return null==h});d=c.h[d].getUniformLocation(c.s[b],c.D(e));-1==f?(f=c.j.length,c.j.push(d)):c.j[f]=d;return f};a.g.getVertexAttrib=function(){alert("getVertexAttrib not implemented");return 0};a.g.getVertexAttribOffset=function(d,b,e){try{return c.h[d].getVertexAttribOffset(b,
e)}catch(f){console.log("getVertexAttribOffset error"),console.error(f)}};a.g.hint=function(d,b,e){try{return c.h[d].hint(b,e)}catch(f){console.log("hint error"),console.error(f)}};a.g.isBuffer=function(d,b){try{return c.h[d].isBuffer(c.F[b])}catch(e){console.log("isBuffer error"),console.error(e)}};a.g.isEnabled=function(d,b){try{return c.h[d].isEnabled(b)}catch(e){console.log("isEnabled error"),console.error(e)}};a.g.isFramebuffer=function(d,b){try{return c.h[d].isFramebuffer(c.ua[b])}catch(e){console.log("isFramebuffer error"),
console.error(e)}};a.g.isProgram=function(d,b){try{return c.h[d].isProgram(c.s[b])}catch(e){console.log("isProgram error"),console.error(e)}};a.g.isRenderbuffer=function(d,b){try{return c.h[d].isRenderbuffer(c.I[b])}catch(e){console.log("isRenderbuffer error"),console.error(e)}};a.g.isShader=function(d,b){try{return c.h[d].isShader(c.B[b])}catch(e){console.log("isShader error"),console.error(e)}};a.g.isTexture=function(d,b){try{return c.h[d].isTexture(c.G[b])}catch(e){console.log("isTexture error"),
console.error(e)}};a.g.lineWidth=function(d,b){try{return c.h[d].lineWidth(b)}catch(e){console.log("lineWidth error"),console.error(e)}};a.g.linkProgram=function(d,b){c.h[d].linkProgram(c.s[b]);c.h[d].getProgramParameter(c.s[b],c.h[d].LINK_STATUS)||console.log(c.h[d].getProgramInfoLog(c.s[b]))};a.g.pixelStorei=function(d,b,e){c.h[d].pixelStorei(b,e)};a.g.polygonOffset=function(d,b,e){try{c.h[d].polygonOffset(b,e)}catch(f){console.log("polygonOffset error"),console.error(f)}};a.g.readPixels=function(){alert("readPixels not implemented")};
a.g.renderbufferStorage=function(d,b,e,f,h){try{c.h[d].renderbufferStorage(b,e,f,h)}catch(m){console.log("renderbufferStorage error"),console.error(m)}};a.g.sampleCoverage=function(d,b,e){try{c.h[d].sampleCoverage(b,e)}catch(f){console.log("sampleCoverage error"),console.error(f)}};a.g.scissor=function(d,b,e,f,h){try{c.h[d].scissor(b,e,f,h)}catch(m){console.log("scissor error"),console.error(m)}};a.g.shaderSource=function(d,b,e){c.h[d].shaderSource(c.B[b],c.D(e))};a.g.stencilFunc=function(d,b,e,f){try{c.h[d].stencilFunc(b,
e,f)}catch(h){console.log("stencilFunc error"),console.error(h)}};a.g.stencilFuncSeparate=function(d,b,e,f,h){try{c.h[d].stencilFuncSeparate(b,e,f,h)}catch(m){console.log("stencilFuncSeparate error"),console.error(m)}};a.g.stencilMask=function(d,b){try{c.h[d].stencilMask(b)}catch(e){console.log("stencilMask error"),console.error(e)}};a.g.stencilMaskSeparate=function(d,b,e){try{c.h[d].stencilMaskSeparate(b,e)}catch(f){console.log("stencilMaskSeparate error"),console.error(f)}};a.g.stencilOp=function(){alert("stencilOp is not implemented")};
a.g.stencilOpSeparate=function(){alert("stencilOpSeparate is not implemented")};a.g.texImage2D=function(d,b,e,f,h,m,n){c.h[d].texImage2D(b,e,f,h,m,c.L[n])};a.g.texParameterf=function(d,b,e,f){try{c.h[d].texParameterf(b,e,f)}catch(h){console.log("texParameterf error"),console.error(h)}};a.g.texParameteri=function(d,b,e,f){c.h[d].texParameteri(b,e,f)};a.g.texSubImage2D=function(d,b,e,f,h,m,n,v,r,t){try{c.h[d].texSubImage2D(b,e,f,h,m,n,v,r,c.o(t))}catch(D){console.log("texSubImage2D error"),console.error(D)}};
a.g.uniform1f=function(d,b,e){try{return c.h[d].uniform1f(c.j[b],e)}catch(f){console.log("uniform1f error"),console.error(f)}};a.g.uniform1fv=function(d,b,e){try{return c.h[d].uniform1fv(c.j[b],c.o(e))}catch(f){console.log("uniform1fv error"),console.error(f)}};a.g.uniform1i=function(d,b,e){return c.h[d].uniform1i(c.j[b],e)};a.g.uniform1iv=function(d,b,e){try{return c.h[d].uniform1iv(c.j[b],c.o(e))}catch(f){console.log("uniform1iv error"),console.error(f)}};a.g.uniform2f=function(d,b,e,f){try{return c.h[d].uniform2f(c.j[b],
e,f)}catch(h){console.log("uniform2f error"),console.error(h)}};a.g.uniform2fv=function(d,b,e){try{return c.h[d].uniform2fv(c.j[b],c.o(e))}catch(f){console.log("uniform2fv error"),console.error(f)}};a.g.uniform2i=function(d,b,e,f){try{return c.h[d].uniform2i(c.j[b],e,f)}catch(h){console.log("uniform2i error"),console.error(h)}};a.g.uniform2iv=function(d,b,e){try{return c.h[d].uniform2iv(c.j[b],c.o(e))}catch(f){console.log("uniform2iv error"),console.error(f)}};a.g.uniform3f=function(d,b,e,f,h){try{return c.h[d].uniform3f(c.j[b],
e,f,h)}catch(m){console.log("uniform3f error"),console.error(m)}};a.g.uniform3fv=function(d,b,e){try{return c.h[d].uniform3fv(c.j[b],new Float32Array(e))}catch(f){console.log("uniform3fv error"),console.error(f)}};a.g.uniform3i=function(d,b,e,f,h){try{return c.h[d].uniform3i(c.j[b],e,f,h)}catch(m){console.log("uniform3i error"),console.error(m)}};a.g.uniform3iv=function(d,b,e){try{return c.h[d].uniform3iv(c.j[b],c.o(e))}catch(f){console.log("uniform3iv error"),console.error(f)}};a.g.uniform4f=function(d,
b,e,f,h,m){try{return c.h[d].uniform4f(c.j[b],e,f,h,m)}catch(n){console.log("uniform4f error"),console.error(n)}};a.g.uniform4fv=function(d,b,e){try{return c.h[d].uniform4fv(c.j[b],c.o(e))}catch(f){console.log("uniform4fv error"),console.error(f)}};a.g.uniform4i=function(d,b,e,f,h,m){try{return c.h[d].uniform4i(c.j[b],e,f,h,m)}catch(n){console.log("uniform4i error"),console.error(n)}};a.g.uniform4iv=function(d,b,e){try{return c.h[d].uniform4iv(c.j[b],c.o(e))}catch(f){console.log("uniform4iv error"),
console.error(f)}};a.g.uniformMatrix2fv=function(d,b,e,f){try{return f>>=2,c.h[d].uniformMatrix3fv(c.j[b],e,(new Float32Array(c.memory.buffer)).subarray(f,f+4))}catch(h){console.log("uniformMatrix2fv error"),console.error(h)}};a.g.uniformMatrix3fv=function(d,b,e,f){try{return f>>=2,c.h[d].uniformMatrix3fv(c.j[b],e,(new Float32Array(c.memory.buffer)).subarray(f,f+9))}catch(h){console.log("uniformMatrix3fv error"),console.error(h)}};a.g.uniformMatrix4fv=function(d,b,e,f){try{return f>>=2,c.h[d].uniformMatrix3fv(c.j[b],
e,(new Float32Array(c.memory.buffer)).subarray(f,f+16))}catch(h){console.log("uniformMatrix4fv error"),console.error(h)}};a.g.useProgram=function(d,b){c.h[d].useProgram(c.s[b])};a.g.validateProgram=function(d,b){try{c.h[d].validateProgram(c.s[b])}catch(e){console.log("validateProgram error"),console.error(e)}};a.g.vertexAttrib1f=function(d,b,e){try{return c.h[d].vertexAttrib1f(b,e)}catch(f){console.log("vertexAttrib1f error"),console.error(f)}};a.g.vertexAttrib1fv=function(d,b,e){try{return c.h[d].vertexAttrib1fv(b,
c.o(e))}catch(f){console.log("vertexAttrib1fv error"),console.error(f)}};a.g.vertexAttrib2f=function(d,b,e,f){try{return c.h[d].vertexAttrib2f(b,e,f)}catch(h){console.log("vertexAttrib2f error"),console.error(h)}};a.g.vertexAttrib2fv=function(d,b,e){try{return c.h[d].vertexAttrib2fv(b,c.o(e))}catch(f){console.log("vertexAttrib2fv error"),console.error(f)}};a.g.vertexAttrib3f=function(d,b,e,f,h){try{return c.h[d].vertexAttrib3f(b,e,f,h)}catch(m){console.log("vertexAttrib3f error"),console.error(m)}};
a.g.vertexAttrib3fv=function(d,b,e){try{return c.h[d].vertexAttrib3fv(b,c.o(e))}catch(f){console.log("vertexAttrib3fv error"),console.error(f)}};a.g.vertexAttrib4f=function(d,b,e,f,h,m){try{return c.h[d].vertexAttrib4f(b,e,f,h,m)}catch(n){console.log("vertexAttrib4f error"),console.error(n)}};a.g.vertexAttrib4fv=function(d,b,e){try{return c.h[d].vertexAttrib4fv(b,c.o(e))}catch(f){console.log("vertexAttrib4fv error"),console.error(f)}};a.g.vertexAttribPointer=function(d,b,e,f,h,m,n){c.h[d].vertexAttribPointer(b,
e,f,h,m,n)};a.g.viewport=function(d,b,e,f,h,m){try{c.h[d].viewport(b,e,f,h,m)}catch(n){console.log("viewport error"),console.error(n)}};a.g.copyBufferSubData=function(){alert("copyBufferSubData not implemented (expiramental)")};a.g.getBufferSubData=function(){alert("getBufferSubData not implemented (expiramental)")};a.g.blitFramebuffer=function(){alert("blitFramebuffer not implemented (expiramental)")};a.g.framebufferTextureLayer=function(){alert("framebufferTextureLayer not implemented (expiramental)")};
a.g.invalidateFramebuffer=function(){alert("invalidateFramebuffer not implemented (expiramental)")};a.g.invalidateSubFramebuffer=function(){alert("invalidateSubFramebuffer not implemented (expiramental)")};a.g.readBuffer=function(){alert("readBuffer not implemented (expiramental)")};a.g.getInternalformatParameter=function(){alert("getInternalformatParameter not implemented (expiramental)")};a.g.renderbufferStorageMultisample=function(){alert("renderbufferStorageMultisample not implemented (expiramental)")};
a.g.texStorage2D=function(){alert("texStorage2D not implemented (expiramental)")};a.g.texStorage3D=function(){alert("texStorage3D not implemented (expiramental)")};a.g.texSubImage3D=function(){alert("texSubImage3D not implemented (expiramental)")};a.g.copyTexSubImage3D=function(){alert("copyTexSubImage3D not implemented (expiramental)")};a.g.compressedTexImage3D=function(){alert("compressedTexImage3D not implemented (expiramental)")};a.g.compressedTexSubImage3D=function(){alert("compressedTexSubImage3D not implemented (expiramental)")};
a.g.getFragDataLocation=function(){alert("getFragDataLocation not implemented (expiramental)")};a.g.uniform1ui=function(){alert("uniform1ui not implemented (expiramental)")};a.g.uniform2ui=function(){alert("uniform2ui not implemented (expiramental)")};a.g.uniform3ui=function(){alert("uniform3ui not implemented (expiramental)")};a.g.uniform4ui=function(){alert("uniform4ui not implemented (expiramental)")};a.g.uniform1uiv=function(){alert("uniform1uiv not implemented (expiramental)")};a.g.uniform2uiv=
function(){alert("uniform2uiv not implemented (expiramental)")};a.g.uniform3uiv=function(){alert("uniform3uiv not implemented (expiramental)")};a.g.uniform4uiv=function(){alert("uniform4uiv not implemented (expiramental)")};a.g.uniformMatrix3x2fv=function(){alert("uniformMatrix3x2fv not implemented (expiramental)")};a.g.uniformMatrix4x2fv=function(){alert("uniformMatrix4x2fv not implemented (expiramental)")};a.g.uniformMatrix2x3fv=function(){alert("uniformMatrix2x3fv not implemented (expiramental)")};
a.g.uniformMatrix4x3fv=function(){alert("uniformMatrix4x3fv not implemented (expiramental)")};a.g.uniformMatrix2x4fv=function(){console.trace("uniformMatrix2x4fv");alert("uniformMatrix2x4fv not implemented (expiramental)")};a.g.uniformMatrix3x4fv=function(){console.trace("uniformMatrix3x4fv");alert("uniformMatrix3x4fv not implemented (expiramental)")};a.g.vertexAttribI4i=function(){console.trace("vertexAttribI4i");alert("vertexAttribI4i not implemented (expiramental)")};a.g.vertexAttribI4iv=function(){console.trace("vertexAttribI4iv");
alert("vertexAttribI4iv not implemented (expiramental)")};a.g.vertexAttribI4ui=function(){console.trace("vertexAttribI4ui");alert("vertexAttribI4ui not implemented (expiramental)")};a.g.vertexAttribI4uiv=function(){console.trace("vertexAttribI4uiv");alert("vertexAttribI4uiv not implemented (expiramental)")};a.g.vertexAttribIPointer=function(){console.trace("vertexAttribIPointer");alert("vertexAttribIPointer not implemented (expiramental)")};a.g.vertexAttribDivisor=function(d,b,e){return c.h[d].vertexAttribDivisor(d,
b,e)};a.g.drawArraysInstanced=function(d,b,e,f,h){return c.h[d].drawArraysInstanced(b,e,f,h)};a.g.drawElementsInstanced=function(d,b,e,f,h,m){try{return c.h[d].drawArraysInstanced(b,e,f,h,m)}catch(n){console.log("drawElementsInstanced error"),console.error(n)}};a.g.drawRangeElements=function(){alert("drawRangeElements not implemented (expiramental)")};a.g.drawBuffers=function(){alert("drawBuffers not implemented (expiramental)")};a.g.clearBufferfv=function(){alert("clearBufferfv not implemented (expiramental)")};
a.g.clearBufferiv=function(){alert("clearBufferiv not implemented (expiramental)")};a.g.clearBufferuiv=function(){alert("clearBufferuiv not implemented (expiramental)")};a.g.clearBufferfi=function(){alert("clearBufferfi not implemented (expiramental)")};a.g.createQuery=function(){alert("createQuery not implemented (expiramental)")};a.g.deleteQuery=function(){alert("deleteQuery not implemented (expiramental)")};a.g.isQuery=function(){alert("isQuery not implemented (expiramental)")};a.g.beginQuery=
function(){alert("beginQuery not implemented (expiramental)")};a.g.endQuery=function(){alert("endQuery not implemented (expiramental)")};a.g.getQuery=function(){alert("getQuery not implemented (expiramental)")};a.g.getQueryParameter=function(){alert("getQueryParameter not implemented (expiramental)")};a.g.createSampler=function(){alert("createSampler not implemented (expiramental)")};a.g.deleteSampler=function(){alert("deleteSampler not implemented (expiramental)")};a.g.isSampler=function(){alert("isSampler not implemented (expiramental)")};
a.g.bindSampler=function(){alert("bindSampler not implemented (expiramental)")};a.g.samplerParameteri=function(){alert("samplerParameteri not implemented (expiramental)")};a.g.samplerParameterf=function(){alert("samplerParameterf not implemented (expiramental)")};a.g.getSamplerParameter=function(){alert("getSamplerParameter not implemented (expiramental)")};a.g.fenceSync=function(){alert("fenceSync not implemented (expiramental)")};a.g.isSync=function(){alert("isSync not implemented (expiramental)")};
a.g.deleteSync=function(){alert("deleteSync not implemented (expiramental)")};a.g.clientWaitSync=function(){alert("clientWaitSync not implemented (expiramental)")};a.g.waitSync=function(){alert("waitSync not implemented (expiramental)")};a.g.getSyncParameter=function(){alert("getSyncParameter not implemented (expiramental)")};a.g.createTransformFeedback=function(){alert("createTransformFeedback not implemented (expiramental)")};a.g.deleteTransformFeedback=function(){alert("deleteTransformFeedback not implemented (expiramental)")};
a.g.isTransformFeedback=function(){alert("isTransformFeedback not implemented (expiramental)")};a.g.bindTransformFeedback=function(){alert("bindTransformFeedback not implemented (expiramental)")};a.g.beginTransformFeedback=function(){alert("beginTransformFeedback not implemented (expiramental)")};a.g.endTransformFeedback=function(){alert("endTransformFeedback not implemented (expiramental)")};a.g.transformFeedbackVaryings=function(){alert("transformFeedbackVaryings not implemented (expiramental)")};
a.g.getTransformFeedbackVarying=function(){alert("getTransformFeedbackVarying not implemented (expiramental)")};a.g.pauseTransformFeedback=function(){alert("pauseTransformFeedback not implemented (expiramental)")};a.g.resumeTransformFeedback=function(){alert("resumeTransformFeedback not implemented (expiramental)")};a.g.bindBufferBase=function(){alert("bindBufferBase not implemented (expiramental)")};a.g.bindBufferRange=function(){alert("bindBufferRange not implemented (expiramental)")};a.g.getIndexedParameter=
function(){alert("getIndexedParameter not implemented (expiramental)")};a.g.getUniformIndices=function(){alert("getUniformIndices not implemented (expiramental)")};a.g.getActiveUniforms=function(){alert("getActiveUniforms not implemented (expiramental)")};a.g.getUniformBlockIndex=function(){alert("getUniformBlockIndex not implemented (expiramental)")};a.g.getActiveUniformBlockParameter=function(){alert("getActiveUniformBlockParameter not implemented (expiramental)")};a.g.getActiveUniformBlockName=
function(){alert("getActiveUniformBlockName not implemented (expiramental)")};a.g.uniformBlockBinding=function(){alert("uniformBlockBinding not implemented (expiramental)")};a.g.createVertexArray=function(d){var b=c.N.findIndex(function(e){return null==e});d=c.h[d].createVertexArray();-1==b?(b=c.N.length,c.N.push(d)):c.N[b]=d;return b};a.g.deleteVertexArray=function(){alert("deleteVertexArray not implemented (expiramental)")};a.g.isVertexArray=function(){alert("isVertexArray not implemented (expiramental)")};
a.g.bindVertexArray=function(d,b){c.h[d].bindVertexArray(c.N[b])}};var qa="undefined"!==typeof BigUint64Array,C=Symbol(),ra=new TextDecoder("utf-16le");function sa(a,g){var k=(new Uint32Array(a))[g+-4>>>2]>>>1;a=new Uint16Array(a,g,k);return 32>=k?String.fromCharCode.apply(String,a):ra.decode(a)}
function ta(a){function g(d,b){return d?sa(d.buffer,b):"<yet unknown>"}var k={},c=a.K=a.K||{};c.abort=c.abort||function(d,b,e,f){var h=k.memory||c.memory;throw Error("abort: "+g(h,d)+" at "+g(h,b)+":"+e+":"+f);};c.trace=c.trace||function(d,b,e){for(var f=[],h=2;h<arguments.length;++h)f[h-2]=arguments[h];console.log("trace: "+g(k.memory||c.memory,d)+(b?" ":"")+f.slice(0,b).join(", "))};c.xa=c.xa||Date.now;a.Math=a.Math||Math;a.Date=a.Date||Date;return k}
function E(){throw Error("Operation requires compiling with --exportRuntime");}
function ua(a,g){function k(l){var q=l;var p=new Uint32Array(h.buffer),u=p[D>>>2];if((q>>>=0)>=u)throw Error("invalid id: "+q);q=p[(D+4>>>2)+2*q];if(!(q&7))throw Error("not an array: "+l+", flags="+q);return q}function c(l,q,p){var u=h.buffer;if(p)switch(l){case 2:return new Float32Array(u);case 3:return new Float64Array(u)}else switch(l){case 0:return new (q?Int8Array:Uint8Array)(u);case 1:return new (q?Int16Array:Uint16Array)(u);case 2:return new (q?Int32Array:Uint32Array)(u);case 3:return new (q?
BigInt64Array:BigUint64Array)(u)}throw Error("unsupported align: "+l);}function d(l){var q=new Uint32Array(h.buffer),p=k(q[l+-8>>>2]),u=31-Math.clz32(p>>>6&31),x=p&4?l:q[l+4>>>2];l=p&2?q[l+12>>>2]:q[x+-4>>>2]>>>u;return c(u,p&2048,p&4096).subarray(x>>>=u,x+l)}function b(l,q,p){return new l(e(l,q,p))}function e(l,q,p){var u=h.buffer,x=new Uint32Array(u);p=x[p+4>>>2];return new l(u,p,x[p+-4>>>2]>>>q)}function f(l,q,p){a["__get"+q]=b.bind(null,l,p);a["__get"+q+"View"]=e.bind(null,l,p)}g=g.exports;var h=
g.memory,m=g.table,n=g.sa||E,v=g.W||E,r=g.X||E,t=g.qa||E,D=g.lb||-1;a.sa=n;a.W=v;a.X=r;a.qa=t;a.kb=function(l){if(null==l)return 0;for(var q=l.length,p=n(q<<1,1),u=new Uint16Array(h.buffer),x=0,G=p>>>1;x<q;++x)u[G+x]=l.charCodeAt(x);return p};a.O=function(l){if(!l)return null;var q=h.buffer;if(1!==(new Uint32Array(q))[l+-8>>>2])throw Error("not a string: "+l);return sa(q,l)};a.$=function(l,q){var p=k(l),u=31-Math.clz32(p>>>6&31),x=q.length,G=n(x<<u,p&4?l:0);if(p&4)l=G;else{v(G);l=n(p&2?16:12,l);r(G);
var J=new Uint32Array(h.buffer);J[l+0>>>2]=G;J[l+4>>>2]=G;J[l+8>>>2]=x<<u;p&2&&(J[l+12>>>2]=x)}J=c(u,p&2048,p&4096);if(p&16384)for(p=0;p<x;++p)J[(G>>>u)+p]=q[p];else J.set(q,G>>>u);return l};a.ib=d;a.gb=function(l){l=d(l);for(var q=l.length,p=Array(q),u=0;u<q;u++)p[u]=l[u];return p};a.hb=function(l){var q=h.buffer,p=(new Uint32Array(q))[l+-4>>>2];return q.slice(l,l+p)};[Int8Array,Uint8Array,Uint8ClampedArray,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array].forEach(function(l){f(l,
l.name,31-Math.clz32(l.BYTES_PER_ELEMENT))});qa&&[BigUint64Array,BigInt64Array].forEach(function(l){f(l,l.name.slice(3),3)});a.jb=function(l,q){var p=new Uint32Array(h.buffer);l=p[l+-8>>>2];if(l<=p[D>>>2]){do{if(l==q)return!0;p=l;l=new Uint32Array(h.buffer);var u=l[D>>>2];if((p>>>=0)>=u)throw Error("invalid id: "+p);l=l[(D+4>>>2)+2*p+1]}while(l)}return!1};a.memory=a.memory||h;a.table=a.table||m;return va(g,a)}function wa(a){return"undefined"!==typeof Response&&a instanceof Response}
function xa(a,g){g=void 0===g?{}:g;var k,c,d,b,e,f;return na(function(h){switch(h.i){case 1:return k=wa,A(h,a,2);case 2:if(k(a=h.m))return h.return(ya(a,g));if(a instanceof WebAssembly.Module){c=a;h.i=3;break}return A(h,WebAssembly.compile(a),4);case 4:c=h.m;case 3:return d=c,b=ta(g),A(h,WebAssembly.instantiate(d,g),5);case 5:return e=h.m,f=ua(b,e),h.return({module:d,instance:e,exports:f})}})}
function ya(a,g){g=void 0===g?{}:g;var k,c,d,b,e;return na(function(f){switch(f.i){case 1:if(WebAssembly.instantiateStreaming){f.i=2;break}k=xa;c=wa;return A(f,a,3);case 3:return f.return(k(c(a=f.m)?a.arrayBuffer():a,g));case 2:return d=ta(g),A(f,WebAssembly.instantiateStreaming(a,g),4);case 4:return b=f.m,e=ua(d,b.instance),f.return(Object.assign({},b,{exports:e}))}})}
function va(a,g){g=void 0===g?{}:g;var k=a.__argumentsLength?function(n){a.__argumentsLength.value=n}:a.__setArgumentsLength||a.__setargc||function(){},c={},d;for(d in a){if(Object.prototype.hasOwnProperty.call(a,d)){c.u=a[d];for(var b=d.split("."),e=g;1<b.length;){var f=b.shift();Object.prototype.hasOwnProperty.call(e,f)||(e[f]={});e=e[f]}b=b[0];f=b.indexOf("#");if(0<=f){var h=b.substring(0,f);c.H=e[h];"undefined"!==typeof c.H&&c.H.prototype||(c.C=function(n){return function(v){for(var r=[],t=0;t<
arguments.length;++t)r[t]=arguments[t];return n.C.Aa(n.C.prototype.constructor.apply(n.C.prototype,[0].concat(w(r))))}}(c),c.C.prototype={valueOf:function(){return this[C]}},c.C.Aa=function(n){return function(v){var r={};return Object.create(n.C.prototype,(r[C]={value:v,writable:!1},r))}}(c),c.H&&Object.getOwnPropertyNames(c.H).forEach(function(n){return function(v){return Object.defineProperty(n.C,v,Object.getOwnPropertyDescriptor(n.H,v))}}(c)),e[h]=c.C);b=b.substring(f+1);e=e[h].prototype;if(/^(get|set):/.test(b))Object.prototype.hasOwnProperty.call(e,
b=b.substring(4))||(c.R=a[d.replace("set:","get:")],c.S=a[d.replace("get:","set:")],Object.defineProperty(e,b,{get:function(n){return function(){return n.R(this[C])}}(c),set:function(n){return function(v){n.S(this[C],v)}}(c),enumerable:!0}));else if("constructor"===b)(e[b]=function(n){return function(v){for(var r=[],t=0;t<arguments.length;++t)r[t]=arguments[t];k(r.length);return n.u.apply(null,w(r))}}(c)).ba=c.u;else{var m=this;(e[b]=function(n){return function(v){for(var r=[],t=0;t<arguments.length;++t)r[t]=
arguments[t];k(r.length);return n.u.apply(null,[m[C]].concat(w(r)))}}(c)).ba=c.u}}else/^(get|set):/.test(b)?Object.prototype.hasOwnProperty.call(e,b=b.substring(4))||Object.defineProperty(e,b,{get:a[d.replace("set:","get:")],set:a[d.replace("get:","set:")],enumerable:!0}):"function"===typeof c.u&&c.u!==k?(e[b]=function(n){return function(v){for(var r=[],t=0;t<arguments.length;++t)r[t]=arguments[t];k(r.length);return n.u.apply(null,w(r))}}(c)).ba=c.u:e[b]=c.u}c={C:c.C,H:c.H,R:c.R,S:c.S,u:c.u}}return g}
;var za=Math.random().toString(36).substr(2,9),Aa,F,H=document.getElementById("cnvs"),Ba=new Audio("audio/replica.mp3"),Ca=new Audio("audio/deadly_slot_game.mp3"),Da=new Audio("audio/aesir_chaos.mp3"),Ea=new Audio("audio/laserSmall_000.ogg"),Fa=new Audio("audio/explosion-hq.mp3"),I="chill",K={chill:Ba,fight1:Ca,fight2:Da},Ga={laser:Ea,explosion:Fa},L=null,M=null,N=null,O=null,P=0,Q=null,R=null,S=100;function Ha(){null!=O&&(O.close(),O=null)}
function Ia(){function a(){Q=setTimeout(function(){F.Ua();a()},S+(20*Math.random()-10));S*=2;1E3<S&&(S=1E3)}F.ma(performance.now());S=100;a();R=setInterval(function(){F.Qa()},100)}function T(){null!=Q&&(clearTimeout(Q),Q=null);null!=R&&(clearInterval(R),R=null);null!=M&&(M.close(),M=null);null!=N&&(N.close(),N=null);null!=L&&(L.close(),L=null);P=0}
function Ja(a){null!=L?console.error("StartRTCPeerConnection: webrtc_conn not null"):(L=new RTCPeerConnection(null),M=L.createDataChannel("unreliable",{ordered:!1,maxPacketLifeTime:100}),M.onopen=function(){P++;2<=P&&F.ma(performance.now())},M.onerror=function(g){console.log("onerror:",M.readyState,g)},M.onclose=function(){F.la();Ha();T()},M.onmessage=function(g){var k=performance.now();g=F.W(F.$(F.oa,new Uint8Array(g.data)));F.Pa(k,g);F.X(g)},M.onbufferedamountlow=function(){},N=L.createDataChannel("reliable",
{ordered:!0,maxRetransmits:1E3}),N.onopen=function(){P++;2<=P&&Ia()},N.onerror=function(g){console.log("onerror:",N.readyState,g)},N.onclose=function(){F.la();Ha();T()},N.onmessage=function(g){g=F.W(F.$(F.oa,new Uint8Array(g.data)));F.Oa(g);F.X(g)},N.onbufferedamountlow=function(){},L.createOffer().then(function(g){return L.setLocalDescription(g)}).then(function(){a(L.localDescription)}).catch(function(g){console.error("createOffer failed: "+g);Ha();T()}))}
function Ka(){O=new WebSocket("wss://"+location.hostname+":8443/bb/"+za);O.onopen=function(){console.log("WebSocket client connected");L||Ja(function(a){null!=O?O.send(JSON.stringify({type:"offer",wb:a})):T()})};O.onclose=function(){console.error("WebSocket client disconnected");O=null;setTimeout(function(){location.reload()},3E3);setTimeout(function(){Ka()},1E3)};O.onerror=function(a){console.error("WebSocket error",a)};O.onmessage=function(a){try{var g=JSON.parse(a.data);"answer"==g.type&&null!=
L?L.setRemoteDescription(new RTCSessionDescription({type:"answer",sdp:g.sdp})):"candidate"==g.type&&null!=L&&L.addIceCandidate(new RTCIceCandidate({candidate:g.candidate,sdpMid:g.mid}))}catch(k){console.error("Websocket message parse failed: err=",k)}}}var U=!1,La=0,Ma=0,V=0,W=0,X=!1;
function Na(){U||(U=!0,document.body.style.backgroundColor="#444",La=parseInt(window.getComputedStyle(H.parentNode).getPropertyValue("margin-left"),10),Ma=parseInt(window.getComputedStyle(H.parentNode).getPropertyValue("margin-top"),10),X&&(K[I].play(),K[I].loop=!0))}function Oa(){U&&(U=!1,W=V=-1,document.body.style.backgroundColor="white",X&&K[I].pause())}
function Pa(a){a.touches?(V=a.targetTouches[0].clientX-La,W=a.targetTouches[0].clientY-Ma):a.offsetX?(V=a.offsetX,W=a.offsetY):a.layerX&&(V=a.layerX,W=a.layerY)}H.addEventListener("touchmove",function(a){a.preventDefault();Pa(a)},{passive:!1});H.addEventListener("MozTouchMove",function(a){a.preventDefault();Pa(a)},{passive:!1});H.addEventListener("mousemove",function(a){Pa(a)},{passive:!0});H.addEventListener("touchstart",function(a){a.preventDefault();Na()},{passive:!1});
H.addEventListener("MozTouchDown",function(a){a.preventDefault();Na()},{passive:!1});H.addEventListener("mouseover",function(){Na()},{passive:!0});H.addEventListener("touchend",function(a){a.preventDefault();Oa()},{passive:!1});H.addEventListener("MozTouchUp",function(a){a.preventDefault();Oa()},{passive:!1});H.addEventListener("mouseout",function(){Oa()},{passive:!0});document.addEventListener("mousedown",function(){X||(X=!0,K[I].play(),K[I].loop=!0)},{passive:!0});var Qa=0,Ra=0,Y=0,Z=0,Sa=0;
function Ta(){(window.innerWidth!=Qa||window.innerHeight!=Ra)&&100<=performance.now()-Sa&&(Qa=window.innerWidth,Ra=window.innerHeight,Y=.98*Qa-32,Z=.98*Ra-32,Y>Z?Y=Z:Z=Y,H.width=Y,H.height=Y,H.style.width=Y+"px",H.style.height=Y+"px",Sa=performance.now());F.Ra(performance.now(),V,W,Y,Z);requestAnimationFrame(Ta)}
var Ua={vb:{mb:function(a){var g=F.O(a);setTimeout(function(){console.log(g)},50)},getMilliseconds:function(){return performance.now()}},client:{Bb:function(a){null!=N&&N.send(F.ra(a))},Cb:function(a){null!=M&&M.send(F.ra(a))},xb:function(a){var g=F.O(a);setTimeout(function(){if(I!=g){var k=I,c=function(){var e=K[k].volume-.1;0>=e?K[k].pause():(K[k].volume=e,setTimeout(c,100))};c()}I=g;if(X){var d=I;K[d].volume=.1;U&&K[d].play();var b=function(){var e=K[d].volume+.1;1>e?(K[d].volume=e,setTimeout(b,
100)):K[d].volume=1};b();K[I].loop=!0}},0)},yb:function(a){var g=F.O(a);setTimeout(function(){X&&(Ga[g].pause(),Ga[g].play())},0)},Eb:function(){console.log("LoginGood")},Db:function(a){a=F.O(a);console.error("LoginBad:",a)}}};
(function(a){var g=new WebAssembly.Memory({initial:1E4}),k=Object.assign({},Ua,{K:{memory:g}});pa(k);(function(){var c;return na(function(d){if(1==d.i)return A(d,fetch(a),2);c=d.m;ya(c,k).then(function(b){Aa=b;F=Aa.exports;console.log("ASWebGLReady");null==b?console.error("ASWebGLReady requires the WebAssembly Instance as 1st parameter"):null==b?console.error("ASWebGLReady requires import object as 2nd parameter"):(k.g.pa=!0,console.log("========================="),console.log(b.instance.exports),
console.log(b.instance.exports.__rtti_base),k.g.U=b.instance.exports.__rtti_base);F.Da();Ka();requestAnimationFrame(Ta)});d.i=0})})()})("client.wasm");
